import type { DutyPolicy, DutyRotationEntry, LeaveGrant, LeaveRequest, Staff, TripRecord } from "./types";
import { addDays, today } from "./date";

// 직급 체계: 사원(근속 0~1년) → 주임(2~3) → 대리(4~5) → 과장(6~8)
// → 차장(9~12) → 부장(13년~). 인원 구성: 부장 2 / 차장 3 / 과장 5 /
// 대리 10 / 주임 6 / 사원 4 = 총 30명.
export const staffList: Staff[] = [
  // 기존 7명 (joinedAt은 그대로, 직급만 근속연수에 맞게 부여)
  { id: "s1", name: "김민준", role: "대리", joinedAt: "2021-03-02" },
  { id: "s2", name: "이서연", role: "과장", joinedAt: "2020-07-14" },
  { id: "s3", name: "박도윤", role: "대리", joinedAt: "2022-01-10" },
  { id: "s4", name: "최지우", role: "과장", joinedAt: "2019-11-25" },
  { id: "s5", name: "정하은", role: "주임", joinedAt: "2023-05-08" },
  { id: "s6", name: "한소율", role: "대리", joinedAt: "2022-09-19" },
  { id: "s7", name: "오채원", role: "주임", joinedAt: "2024-02-01" },
  // 신규 23명
  { id: "s8", name: "서준영", role: "부장", joinedAt: "2011-04-12" },
  { id: "s9", name: "김도현", role: "부장", joinedAt: "2008-02-20" },
  { id: "s10", name: "이하은", role: "차장", joinedAt: "2017-06-15" },
  { id: "s11", name: "박지훈", role: "차장", joinedAt: "2016-08-03" },
  { id: "s12", name: "최수빈", role: "차장", joinedAt: "2014-01-27" },
  { id: "s13", name: "정민재", role: "과장", joinedAt: "2020-05-19" },
  { id: "s14", name: "강서율", role: "과장", joinedAt: "2019-09-10" },
  { id: "s15", name: "조은서", role: "과장", joinedAt: "2018-03-30" },
  { id: "s16", name: "윤태양", role: "대리", joinedAt: "2022-07-08" },
  { id: "s17", name: "장예린", role: "대리", joinedAt: "2022-02-14" },
  { id: "s18", name: "임현우", role: "대리", joinedAt: "2021-05-05" },
  { id: "s19", name: "한지민", role: "대리", joinedAt: "2021-08-22" },
  { id: "s20", name: "오세진", role: "대리", joinedAt: "2022-01-16" },
  { id: "s21", name: "신유진", role: "대리", joinedAt: "2021-03-11" },
  { id: "s22", name: "권민석", role: "대리", joinedAt: "2022-09-01" },
  { id: "s23", name: "황수아", role: "주임", joinedAt: "2024-04-25" },
  { id: "s24", name: "안준서", role: "주임", joinedAt: "2023-06-07" },
  { id: "s25", name: "송지호", role: "주임", joinedAt: "2024-08-14" },
  { id: "s26", name: "전예은", role: "주임", joinedAt: "2023-02-28" },
  { id: "s27", name: "홍성민", role: "사원", joinedAt: "2026-03-01" },
  { id: "s28", name: "유하늘", role: "사원", joinedAt: "2025-06-10" },
  { id: "s29", name: "고은채", role: "사원", joinedAt: "2026-01-20" },
  { id: "s30", name: "문재원", role: "사원", joinedAt: "2025-02-14" },
];

const t = today();
export const CURRENT_YEAR = t.getFullYear();

// 연차 발생일수(granted)는 이제 근로기준법 기준으로 자동 계산되므로
// (computeAnnualLeaveDays 참고) 이 레코드는 이월/조정 값만 담는다.
export const initialLeaveGrants: LeaveGrant[] = [];

export const initialDutyPolicy: DutyPolicy = {
  weekendIncluded: true,
  holidayIncluded: true,
  autoExcludeOnLeave: true,
  selectionDeadline: "18:00",
};

export const initialDutyRotation: DutyRotationEntry[] = staffList.map((s, i) => ({
  staffId: s.id,
  order: i + 1,
  active: true,
}));

export const emergencyContacts: Record<string, string> = {
  s1: "010-1234-5671",
  s2: "010-1234-5672",
  s3: "010-1234-5673",
  s4: "010-1234-5674",
  s5: "010-1234-5675",
  s6: "010-1234-5676",
  s7: "010-1234-5677",
};
// 신규 23명(s8~s30)은 순번 기반으로 생성
for (let i = 8; i <= 30; i++) {
  emergencyContacts[`s${i}`] = `010-2000-${String(i).padStart(4, "0")}`;
}

export const handoverPartners: Record<string, string> = {
  s1: "s3",
  s2: "s1",
  s3: "s5",
  s4: "s2",
  s5: "s4",
  s6: "s7",
  s7: "s6",
};
// 신규 23명(s8~s30)은 원형으로 서로 인수인계자를 맡음 (s8→s9→...→s30→s8)
for (let i = 8; i <= 30; i++) {
  const nextId = i === 30 ? 8 : i + 1;
  handoverPartners[`s${i}`] = `s${nextId}`;
}

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: "lr1",
    staffId: "s1",
    type: "연차",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s1,
    emergencyContact: emergencyContacts.s1,
    status: "승인",
    requestedAt: addDays(t, -5),
    decidedAt: addDays(t, -4),
    decidedBy: "박기표",
  },
  {
    id: "lr2",
    staffId: "s3",
    type: "반차(오후)",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s3,
    emergencyContact: emergencyContacts.s3,
    status: "승인",
    requestedAt: addDays(t, -2),
    decidedAt: addDays(t, -1),
    decidedBy: "박기표",
  },
  {
    id: "lr3",
    staffId: "s4",
    type: "연차",
    startDate: addDays(t, 2),
    endDate: addDays(t, 3),
    days: 2,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s4,
    emergencyContact: emergencyContacts.s4,
    status: "승인대기",
    requestedAt: addDays(t, -1),
  },
  {
    id: "lr4",
    staffId: "s5",
    type: "경조사",
    startDate: addDays(t, 6),
    endDate: addDays(t, 8),
    days: 3,
    reason: "가족 경조사",
    handoverStaffId: handoverPartners.s5,
    emergencyContact: emergencyContacts.s5,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr5",
    staffId: "s2",
    type: "연차",
    startDate: addDays(t, -10),
    endDate: addDays(t, -10),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s2,
    emergencyContact: emergencyContacts.s2,
    status: "반려",
    requestedAt: addDays(t, -12),
    decidedAt: addDays(t, -11),
    decidedBy: "박기표",
  },
  {
    id: "lr6",
    staffId: "s6",
    type: "반차(오전)",
    startDate: addDays(t, 1),
    endDate: addDays(t, 1),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s6,
    emergencyContact: emergencyContacts.s6,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr7",
    staffId: "s7",
    type: "병가",
    startDate: addDays(t, -3),
    endDate: addDays(t, -2),
    days: 2,
    reason: "몸살감기",
    handoverStaffId: handoverPartners.s7,
    emergencyContact: emergencyContacts.s7,
    status: "승인",
    requestedAt: addDays(t, -3),
    decidedAt: addDays(t, -3),
    decidedBy: "박기표",
  },
  {
    id: "lr8",
    staffId: "s2",
    type: "연차",
    startDate: addDays(t, -80),
    endDate: addDays(t, -76),
    days: 5,
    reason: "여름 휴가",
    handoverStaffId: handoverPartners.s2,
    emergencyContact: emergencyContacts.s2,
    status: "승인",
    requestedAt: addDays(t, -90),
    decidedAt: addDays(t, -89),
    decidedBy: "박기표",
  },
  {
    id: "lr9",
    staffId: "s2",
    type: "연차",
    startDate: addDays(t, -45),
    endDate: addDays(t, -41),
    days: 4.5,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s2,
    emergencyContact: emergencyContacts.s2,
    status: "승인",
    requestedAt: addDays(t, -50),
    decidedAt: addDays(t, -49),
    decidedBy: "박기표",
  },
  {
    id: "lr10",
    staffId: "s4",
    type: "연차",
    startDate: addDays(t, -70),
    endDate: addDays(t, -59),
    days: 10,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s4,
    emergencyContact: emergencyContacts.s4,
    status: "승인",
    requestedAt: addDays(t, -80),
    decidedAt: addDays(t, -79),
    decidedBy: "박기표",
  },
  {
    id: "lr11",
    staffId: "s4",
    type: "연차",
    startDate: addDays(t, -30),
    endDate: addDays(t, -29),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s4,
    emergencyContact: emergencyContacts.s4,
    status: "승인",
    requestedAt: addDays(t, -35),
    decidedAt: addDays(t, -34),
    decidedBy: "박기표",
  },
  {
    id: "lr12",
    staffId: "s6",
    type: "연차",
    startDate: addDays(t, -20),
    endDate: addDays(t, -16),
    days: 4,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s6,
    emergencyContact: emergencyContacts.s6,
    status: "승인",
    requestedAt: addDays(t, -25),
    decidedAt: addDays(t, -24),
    decidedBy: "박기표",
  },
  // 신규 23명(s8~s30)의 휴가 사용 이력
  {
    id: "lr13",
    staffId: "s8",
    type: "연차",
    startDate: addDays(t, -60),
    endDate: addDays(t, -56),
    days: 5,
    reason: "여름 휴가",
    handoverStaffId: handoverPartners.s8,
    emergencyContact: emergencyContacts.s8,
    status: "승인",
    requestedAt: addDays(t, -65),
    decidedAt: addDays(t, -64),
    decidedBy: "박기표",
  },
  {
    id: "lr14",
    staffId: "s9",
    type: "연차",
    startDate: addDays(t, -40),
    endDate: addDays(t, -36),
    days: 5,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s9,
    emergencyContact: emergencyContacts.s9,
    status: "승인",
    requestedAt: addDays(t, -45),
    decidedAt: addDays(t, -44),
    decidedBy: "박기표",
  },
  {
    id: "lr15",
    staffId: "s10",
    type: "연차",
    startDate: addDays(t, -30),
    endDate: addDays(t, -28),
    days: 3,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s10,
    emergencyContact: emergencyContacts.s10,
    status: "승인",
    requestedAt: addDays(t, -35),
    decidedAt: addDays(t, -34),
    decidedBy: "박기표",
  },
  {
    id: "lr16",
    staffId: "s10",
    type: "연차",
    startDate: addDays(t, 5),
    endDate: addDays(t, 6),
    days: 2,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s10,
    emergencyContact: emergencyContacts.s10,
    status: "승인대기",
    requestedAt: addDays(t, -1),
  },
  {
    id: "lr17",
    staffId: "s11",
    type: "병가",
    startDate: addDays(t, -15),
    endDate: addDays(t, -14),
    days: 2,
    reason: "몸살감기",
    handoverStaffId: handoverPartners.s11,
    emergencyContact: emergencyContacts.s11,
    status: "승인",
    requestedAt: addDays(t, -15),
    decidedAt: addDays(t, -15),
    decidedBy: "박기표",
  },
  {
    id: "lr18",
    staffId: "s12",
    type: "연차",
    startDate: addDays(t, -90),
    endDate: addDays(t, -86),
    days: 5,
    reason: "여름 휴가",
    handoverStaffId: handoverPartners.s12,
    emergencyContact: emergencyContacts.s12,
    status: "승인",
    requestedAt: addDays(t, -95),
    decidedAt: addDays(t, -94),
    decidedBy: "박기표",
  },
  {
    id: "lr19",
    staffId: "s13",
    type: "연차",
    startDate: addDays(t, -25),
    endDate: addDays(t, -24),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s13,
    emergencyContact: emergencyContacts.s13,
    status: "승인",
    requestedAt: addDays(t, -30),
    decidedAt: addDays(t, -29),
    decidedBy: "박기표",
  },
  {
    id: "lr20",
    staffId: "s14",
    type: "반차(오전)",
    startDate: addDays(t, -10),
    endDate: addDays(t, -10),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s14,
    emergencyContact: emergencyContacts.s14,
    status: "승인",
    requestedAt: addDays(t, -11),
    decidedAt: addDays(t, -11),
    decidedBy: "박기표",
  },
  {
    id: "lr21",
    staffId: "s15",
    type: "경조사",
    startDate: addDays(t, -50),
    endDate: addDays(t, -48),
    days: 3,
    reason: "가족 경조사",
    handoverStaffId: handoverPartners.s15,
    emergencyContact: emergencyContacts.s15,
    status: "승인",
    requestedAt: addDays(t, -52),
    decidedAt: addDays(t, -51),
    decidedBy: "박기표",
  },
  {
    id: "lr22",
    staffId: "s16",
    type: "연차",
    startDate: addDays(t, -5),
    endDate: addDays(t, -4),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s16,
    emergencyContact: emergencyContacts.s16,
    status: "승인",
    requestedAt: addDays(t, -8),
    decidedAt: addDays(t, -7),
    decidedBy: "박기표",
  },
  {
    id: "lr23",
    staffId: "s16",
    type: "반차(오후)",
    startDate: addDays(t, 2),
    endDate: addDays(t, 2),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s16,
    emergencyContact: emergencyContacts.s16,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr24",
    staffId: "s17",
    type: "반차(오후)",
    startDate: addDays(t, -3),
    endDate: addDays(t, -3),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s17,
    emergencyContact: emergencyContacts.s17,
    status: "승인",
    requestedAt: addDays(t, -4),
    decidedAt: addDays(t, -4),
    decidedBy: "박기표",
  },
  {
    id: "lr25",
    staffId: "s18",
    type: "연차",
    startDate: addDays(t, -20),
    endDate: addDays(t, -19),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s18,
    emergencyContact: emergencyContacts.s18,
    status: "승인",
    requestedAt: addDays(t, -23),
    decidedAt: addDays(t, -22),
    decidedBy: "박기표",
  },
  {
    id: "lr26",
    staffId: "s19",
    type: "병가",
    startDate: addDays(t, -7),
    endDate: addDays(t, -6),
    days: 2,
    reason: "몸살감기",
    handoverStaffId: handoverPartners.s19,
    emergencyContact: emergencyContacts.s19,
    status: "승인",
    requestedAt: addDays(t, -7),
    decidedAt: addDays(t, -7),
    decidedBy: "박기표",
  },
  {
    id: "lr27",
    staffId: "s19",
    type: "반차(오전)",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s19,
    emergencyContact: emergencyContacts.s19,
    status: "승인",
    requestedAt: addDays(t, -1),
    decidedAt: addDays(t, -1),
    decidedBy: "박기표",
  },
  {
    id: "lr28",
    staffId: "s20",
    type: "연차",
    startDate: addDays(t, -2),
    endDate: addDays(t, -2),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s20,
    emergencyContact: emergencyContacts.s20,
    status: "승인",
    requestedAt: addDays(t, -4),
    decidedAt: addDays(t, -3),
    decidedBy: "박기표",
  },
  {
    id: "lr29",
    staffId: "s21",
    type: "반차(오전)",
    startDate: addDays(t, -1),
    endDate: addDays(t, -1),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s21,
    emergencyContact: emergencyContacts.s21,
    status: "승인",
    requestedAt: addDays(t, -2),
    decidedAt: addDays(t, -2),
    decidedBy: "박기표",
  },
  {
    id: "lr30",
    staffId: "s22",
    type: "연차",
    startDate: addDays(t, -35),
    endDate: addDays(t, -33),
    days: 3,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s22,
    emergencyContact: emergencyContacts.s22,
    status: "승인",
    requestedAt: addDays(t, -40),
    decidedAt: addDays(t, -39),
    decidedBy: "박기표",
  },
  {
    id: "lr31",
    staffId: "s23",
    type: "연차",
    startDate: addDays(t, -12),
    endDate: addDays(t, -11),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s23,
    emergencyContact: emergencyContacts.s23,
    status: "승인",
    requestedAt: addDays(t, -15),
    decidedAt: addDays(t, -14),
    decidedBy: "박기표",
  },
  {
    id: "lr32",
    staffId: "s23",
    type: "연차",
    startDate: addDays(t, 10),
    endDate: addDays(t, 12),
    days: 3,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s23,
    emergencyContact: emergencyContacts.s23,
    status: "승인대기",
    requestedAt: addDays(t, -1),
  },
  {
    id: "lr33",
    staffId: "s24",
    type: "반차(오후)",
    startDate: addDays(t, -6),
    endDate: addDays(t, -6),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s24,
    emergencyContact: emergencyContacts.s24,
    status: "승인",
    requestedAt: addDays(t, -7),
    decidedAt: addDays(t, -7),
    decidedBy: "박기표",
  },
  {
    id: "lr34",
    staffId: "s25",
    type: "연차",
    startDate: addDays(t, -18),
    endDate: addDays(t, -18),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s25,
    emergencyContact: emergencyContacts.s25,
    status: "승인",
    requestedAt: addDays(t, -20),
    decidedAt: addDays(t, -19),
    decidedBy: "박기표",
  },
  {
    id: "lr35",
    staffId: "s26",
    type: "병가",
    startDate: addDays(t, -9),
    endDate: addDays(t, -8),
    days: 2,
    reason: "몸살감기",
    handoverStaffId: handoverPartners.s26,
    emergencyContact: emergencyContacts.s26,
    status: "승인",
    requestedAt: addDays(t, -9),
    decidedAt: addDays(t, -9),
    decidedBy: "박기표",
  },
  {
    id: "lr36",
    staffId: "s27",
    type: "반차(오전)",
    startDate: addDays(t, -2),
    endDate: addDays(t, -2),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s27,
    emergencyContact: emergencyContacts.s27,
    status: "승인",
    requestedAt: addDays(t, -3),
    decidedAt: addDays(t, -3),
    decidedBy: "박기표",
  },
  {
    id: "lr37",
    staffId: "s28",
    type: "연차",
    startDate: addDays(t, -40),
    endDate: addDays(t, -39),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s28,
    emergencyContact: emergencyContacts.s28,
    status: "승인",
    requestedAt: addDays(t, -42),
    decidedAt: addDays(t, -41),
    decidedBy: "박기표",
  },
  {
    id: "lr38",
    staffId: "s29",
    type: "반차(오후)",
    startDate: addDays(t, -4),
    endDate: addDays(t, -4),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s29,
    emergencyContact: emergencyContacts.s29,
    status: "승인",
    requestedAt: addDays(t, -5),
    decidedAt: addDays(t, -5),
    decidedBy: "박기표",
  },
  {
    id: "lr39",
    staffId: "s30",
    type: "연차",
    startDate: addDays(t, -25),
    endDate: addDays(t, -24),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s30,
    emergencyContact: emergencyContacts.s30,
    status: "승인",
    requestedAt: addDays(t, -28),
    decidedAt: addDays(t, -27),
    decidedBy: "박기표",
  },
];

export const initialTripRecords: TripRecord[] = [
  {
    id: "tr1",
    staffId: "s1",
    type: "출장",
    startDate: addDays(t, 2),
    endDate: addDays(t, 3),
    purpose: "대전 협력사 미팅",
    reachable: true,
    requestedAt: addDays(t, 0),
  },
  {
    id: "tr2",
    staffId: "s2",
    type: "외출",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    startTime: "14:00",
    endTime: "16:00",
    purpose: "은행 업무",
    reachable: true,
    requestedAt: addDays(t, 0),
  },
  {
    id: "tr3",
    staffId: "s6",
    type: "외출",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    startTime: "10:30",
    endTime: "11:30",
    purpose: "병원 진료",
    reachable: false,
    requestedAt: addDays(t, 0),
  },
  // 신규 23명(s8~s30)의 출장·외출
  {
    id: "tr4",
    staffId: "s8",
    type: "출장",
    startDate: addDays(t, 3),
    endDate: addDays(t, 4),
    purpose: "본사 임원 회의",
    reachable: true,
    requestedAt: addDays(t, -1),
  },
  {
    id: "tr5",
    staffId: "s13",
    type: "외출",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    startTime: "11:00",
    endTime: "12:00",
    purpose: "거래처 미팅",
    reachable: true,
    requestedAt: addDays(t, 0),
  },
  {
    id: "tr6",
    staffId: "s17",
    type: "외출",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    startTime: "15:00",
    endTime: "16:30",
    purpose: "은행 업무",
    reachable: true,
    requestedAt: addDays(t, 0),
  },
  {
    id: "tr7",
    staffId: "s24",
    type: "출장",
    startDate: addDays(t, 1),
    endDate: addDays(t, 2),
    purpose: "지방 협력사 방문",
    reachable: false,
    requestedAt: addDays(t, -1),
  },
  {
    id: "tr8",
    staffId: "s20",
    type: "외출",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    startTime: "13:30",
    endTime: "14:30",
    purpose: "병원 진료",
    reachable: true,
    requestedAt: addDays(t, 0),
  },
];
