import type { DutyPolicy, DutyRotationEntry, LeaveGrant, LeaveRequest, Staff, TripRecord } from "./types";
import { addDays, today } from "./date";

export const staffList: Staff[] = [
  { id: "s1", name: "김민준", role: "담당자", joinedAt: "2021-03-02" },
  { id: "s2", name: "이서연", role: "담당자", joinedAt: "2020-07-14" },
  { id: "s3", name: "박도윤", role: "담당자", joinedAt: "2022-01-10" },
  { id: "s4", name: "최지우", role: "담당자", joinedAt: "2019-11-25" },
  { id: "s5", name: "정하은", role: "담당자", joinedAt: "2023-05-08" },
  { id: "s6", name: "한소율", role: "서무", joinedAt: "2022-09-19" },
  { id: "s7", name: "오채원", role: "서무", joinedAt: "2024-02-01" },
];

const t = today();
export const CURRENT_YEAR = t.getFullYear();

export const initialLeaveGrants: LeaveGrant[] = [
  { staffId: "s1", year: CURRENT_YEAR, granted: 15, carryover: 0, adjustment: 0 },
  { staffId: "s2", year: CURRENT_YEAR, granted: 16, carryover: 0, adjustment: 0 },
  { staffId: "s3", year: CURRENT_YEAR, granted: 15, carryover: 0, adjustment: 0 },
  { staffId: "s4", year: CURRENT_YEAR, granted: 17, carryover: 0, adjustment: 0 },
  { staffId: "s5", year: CURRENT_YEAR, granted: 11, carryover: 0, adjustment: 0 },
  { staffId: "s6", year: CURRENT_YEAR, granted: 15, carryover: 0, adjustment: 0 },
  { staffId: "s7", year: CURRENT_YEAR, granted: 9, carryover: 0, adjustment: 0 },
];

export const initialDutyPolicy: DutyPolicy = {
  weekendIncluded: true,
  holidayIncluded: true,
  autoExcludeOnLeave: true,
  selectionDeadline: "18:00",
};

export const initialDutyRotation: DutyRotationEntry[] = staffList.map((s, i) => ({
  staffId: s.id,
  order: i + 1,
  active: true,
}));

export const emergencyContacts: Record<string, string> = {
  s1: "010-1234-5671",
  s2: "010-1234-5672",
  s3: "010-1234-5673",
  s4: "010-1234-5674",
  s5: "010-1234-5675",
  s6: "010-1234-5676",
  s7: "010-1234-5677",
};

export const handoverPartners: Record<string, string> = {
  s1: "s3",
  s2: "s1",
  s3: "s5",
  s4: "s2",
  s5: "s4",
  s6: "s7",
  s7: "s6",
};

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: "lr1",
    staffId: "s1",
    type: "연차",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s1,
    emergencyContact: emergencyContacts.s1,
    status: "승인",
    requestedAt: addDays(t, -5),
    decidedAt: addDays(t, -4),
    decidedBy: "박기표",
  },
  {
    id: "lr2",
    staffId: "s3",
    type: "반차(오후)",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s3,
    emergencyContact: emergencyContacts.s3,
    status: "승인",
    requestedAt: addDays(t, -2),
    decidedAt: addDays(t, -1),
    decidedBy: "박기표",
  },
  {
    id: "lr3",
    staffId: "s4",
    type: "연차",
    startDate: addDays(t, 2),
    endDate: addDays(t, 3),
    days: 2,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s4,
    emergencyContact: emergencyContacts.s4,
    status: "승인대기",
    requestedAt: addDays(t, -1),
  },
  {
    id: "lr4",
    staffId: "s5",
    type: "경조사",
    startDate: addDays(t, 6),
    endDate: addDays(t, 8),
    days: 3,
    reason: "가족 경조사",
    handoverStaffId: handoverPartners.s5,
    emergencyContact: emergencyContacts.s5,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr5",
    staffId: "s2",
    type: "연차",
    startDate: addDays(t, -10),
    endDate: addDays(t, -10),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s2,
    emergencyContact: emergencyContacts.s2,
    status: "반려",
    requestedAt: addDays(t, -12),
    decidedAt: addDays(t, -11),
    decidedBy: "박기표",
  },
  {
    id: "lr6",
    staffId: "s6",
    type: "반차(오전)",
    startDate: addDays(t, 1),
    endDate: addDays(t, 1),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s6,
    emergencyContact: emergencyContacts.s6,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr7",
    staffId: "s7",
    type: "병가",
    startDate: addDays(t, -3),
    endDate: addDays(t, -2),
    days: 2,
    reason: "몸살감기",
    handoverStaffId: handoverPartners.s7,
    emergencyContact: emergencyContacts.s7,
    status: "승인",
    requestedAt: addDays(t, -3),
    decidedAt: addDays(t, -3),
    decidedBy: "박기표",
  },
  {
    id: "lr8",
    staffId: "s2",
    type: "연차",
    startDate: addDays(t, -80),
    endDate: addDays(t, -76),
    days: 5,
    reason: "여름 휴가",
    handoverStaffId: handoverPartners.s2,
    emergencyContact: emergencyContacts.s2,
    status: "승인",
    requestedAt: addDays(t, -90),
    decidedAt: addDays(t, -89),
    decidedBy: "박기표",
  },
  {
    id: "lr9",
    staffId: "s2",
    type: "연차",
    startDate: addDays(t, -45),
    endDate: addDays(t, -41),
    days: 4.5,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s2,
    emergencyContact: emergencyContacts.s2,
    status: "승인",
    requestedAt: addDays(t, -50),
    decidedAt: addDays(t, -49),
    decidedBy: "박기표",
  },
  {
    id: "lr10",
    staffId: "s4",
    type: "연차",
    startDate: addDays(t, -70),
    endDate: addDays(t, -59),
    days: 10,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s4,
    emergencyContact: emergencyContacts.s4,
    status: "승인",
    requestedAt: addDays(t, -80),
    decidedAt: addDays(t, -79),
    decidedBy: "박기표",
  },
  {
    id: "lr11",
    staffId: "s4",
    type: "연차",
    startDate: addDays(t, -30),
    endDate: addDays(t, -29),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s4,
    emergencyContact: emergencyContacts.s4,
    status: "승인",
    requestedAt: addDays(t, -35),
    decidedAt: addDays(t, -34),
    decidedBy: "박기표",
  },
  {
    id: "lr12",
    staffId: "s6",
    type: "연차",
    startDate: addDays(t, -20),
    endDate: addDays(t, -16),
    days: 4,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s6,
    emergencyContact: emergencyContacts.s6,
    status: "승인",
    requestedAt: addDays(t, -25),
    decidedAt: addDays(t, -24),
    decidedBy: "박기표",
  },
];

export const initialTripRecords: TripRecord[] = [
  {
    id: "tr1",
    staffId: "s1",
    type: "출장",
    startDate: addDays(t, 2),
    endDate: addDays(t, 3),
    purpose: "대전 협력사 미팅",
    reachable: true,
    requestedAt: addDays(t, 0),
  },
  {
    id: "tr2",
    staffId: "s2",
    type: "외출",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    startTime: "14:00",
    endTime: "16:00",
    purpose: "은행 업무",
    reachable: true,
    requestedAt: addDays(t, 0),
  },
  {
    id: "tr3",
    staffId: "s6",
    type: "외출",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    startTime: "10:30",
    endTime: "11:30",
    purpose: "병원 진료",
    reachable: false,
    requestedAt: addDays(t, 0),
  },
];
