import type { DutyPolicy, DutyRotationEntry, LeaveGrant, LeaveRequest, Staff, TripRecord } from "./types";
import { addDays, today } from "./date";
import { compareStaffSeniority } from "./staff-order";
import type { LeavePromotionNotice } from "./leave-promotion";

// 직급 체계: 사원(근속 0~1년) → 주임(2~3) → 대리(4~5) → 과장(6~8)
// → 차장(9~12) → 부장(13년~). 인원 구성: 부장 2 / 차장 3 / 과장 5 /
// 대리 10 / 주임 6 / 사원 4 = 총 30명.
//
// 아래 배열은 입력 순서(기존 7명 + 신규 23명)이고, 실제로 내보내는
// staffList는 직급 높은 순 → 같은 직급 내 입사일 빠른 순으로 정렬한
// 결과다. 직원 목록이 나열되는 모든 화면(오늘 현황, 연차 부여, 당직
// 대기열 등)이 이 배열을 그대로 쓰므로 한 곳만 정렬하면 전체에
// 일괄 반영된다.
const rawStaffList: Staff[] = [
  // 기존 7명 (joinedAt은 그대로, 직급만 근속연수에 맞게 부여)
  { id: "s1", name: "김민준", role: "대리", joinedAt: "2021-03-02" },
  { id: "s2", name: "이서연", role: "과장", joinedAt: "2020-07-14" },
  { id: "s3", name: "박도윤", role: "대리", joinedAt: "2022-01-10" },
  { id: "s4", name: "최지우", role: "과장", joinedAt: "2019-11-25" },
  { id: "s5", name: "정하은", role: "주임", joinedAt: "2023-05-08" },
  { id: "s6", name: "한소율", role: "대리", joinedAt: "2022-09-19" },
  { id: "s7", name: "오채원", role: "주임", joinedAt: "2024-02-01" },
  // 신규 23명
  { id: "s8", name: "서준영", role: "부장", joinedAt: "2011-04-12" },
  { id: "s9", name: "김도현", role: "부장", joinedAt: "2008-02-20" },
  { id: "s10", name: "이하은", role: "차장", joinedAt: "2017-06-15" },
  { id: "s11", name: "박지훈", role: "차장", joinedAt: "2016-08-03" },
  { id: "s12", name: "최수빈", role: "차장", joinedAt: "2014-01-27" },
  { id: "s13", name: "정민재", role: "과장", joinedAt: "2020-05-19" },
  { id: "s14", name: "강서율", role: "과장", joinedAt: "2019-09-10" },
  { id: "s15", name: "조은서", role: "과장", joinedAt: "2018-03-30" },
  { id: "s16", name: "윤태양", role: "대리", joinedAt: "2022-07-08" },
  { id: "s17", name: "장예린", role: "대리", joinedAt: "2022-02-14" },
  { id: "s18", name: "임현우", role: "대리", joinedAt: "2021-05-05" },
  { id: "s19", name: "한지민", role: "대리", joinedAt: "2021-08-22" },
  { id: "s20", name: "오세진", role: "대리", joinedAt: "2022-01-16" },
  { id: "s21", name: "신유진", role: "대리", joinedAt: "2021-03-11" },
  { id: "s22", name: "권민석", role: "대리", joinedAt: "2022-09-01" },
  { id: "s23", name: "황수아", role: "주임", joinedAt: "2024-04-25" },
  { id: "s24", name: "안준서", role: "주임", joinedAt: "2023-06-07" },
  { id: "s25", name: "송지호", role: "주임", joinedAt: "2024-08-14" },
  { id: "s26", name: "전예은", role: "주임", joinedAt: "2023-02-28" },
  { id: "s27", name: "홍성민", role: "사원", joinedAt: "2026-03-01" },
  { id: "s28", name: "유하늘", role: "사원", joinedAt: "2025-06-10" },
  { id: "s29", name: "고은채", role: "사원", joinedAt: "2026-01-20" },
  { id: "s30", name: "문재원", role: "사원", joinedAt: "2025-02-14" },
];

export const staffList: Staff[] = [...rawStaffList].sort(compareStaffSeniority);

const t = today();
export const CURRENT_YEAR = t.getFullYear();

// 연차 발생일수(granted)는 이제 근로기준법 기준으로 자동 계산되므로
// (computeAnnualLeaveDays 참고) 이 레코드는 이월/조정 값만 담는다.
export const initialLeaveGrants: LeaveGrant[] = [];

export const initialDutyPolicy: DutyPolicy = {
  weekendIncluded: true,
  holidayIncluded: true,
  autoExcludeOnLeave: true,
  excludeEntryLevel: false,
  excludeDeptHead: false,
  selectionDeadline: "18:00",
};

export const initialDutyRotation: DutyRotationEntry[] = staffList.map((s, i) => ({
  staffId: s.id,
  order: i + 1,
  active: true,
}));

export const emergencyContacts: Record<string, string> = {
  s1: "010-1234-5671",
  s2: "010-1234-5672",
  s3: "010-1234-5673",
  s4: "010-1234-5674",
  s5: "010-1234-5675",
  s6: "010-1234-5676",
  s7: "010-1234-5677",
};
// 신규 23명(s8~s30)은 순번 기반으로 생성
for (let i = 8; i <= 30; i++) {
  emergencyContacts[`s${i}`] = `010-2000-${String(i).padStart(4, "0")}`;
}

export const handoverPartners: Record<string, string> = {
  s1: "s3",
  s2: "s1",
  s3: "s5",
  s4: "s2",
  s5: "s4",
  s6: "s7",
  s7: "s6",
};
// 신규 23명(s8~s30)은 원형으로 서로 인수인계자를 맡음 (s8→s9→...→s30→s8)
for (let i = 8; i <= 30; i++) {
  const nextId = i === 30 ? 8 : i + 1;
  handoverPartners[`s${i}`] = `s${nextId}`;
}

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: "lr1",
    staffId: "s1",
    type: "연차",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s1,
    emergencyContact: emergencyContacts.s1,
    status: "승인",
    requestedAt: addDays(t, -5),
    decidedAt: addDays(t, -4),
    decidedBy: "박기표",
  },
  {
    id: "lr2",
    staffId: "s3",
    type: "반차(오후)",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s3,
    emergencyContact: emergencyContacts.s3,
    status: "승인",
    requestedAt: addDays(t, -2),
    decidedAt: addDays(t, -1),
    decidedBy: "박기표",
  },
  {
    id: "lr3",
    staffId: "s4",
    type: "연차",
    startDate: addDays(t, 2),
    endDate: addDays(t, 3),
    days: 2,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s4,
    emergencyContact: emergencyContacts.s4,
    status: "승인대기",
    requestedAt: addDays(t, -1),
  },
  {
    id: "lr4",
    staffId: "s5",
    type: "경조사",
    startDate: addDays(t, 6),
    endDate: addDays(t, 8),
    days: 3,
    reason: "가족 경조사",
    handoverStaffId: handoverPartners.s5,
    emergencyContact: emergencyContacts.s5,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr5",
    staffId: "s2",
    type: "연차",
    startDate: addDays(t, -10),
    endDate: addDays(t, -10),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s2,
    emergencyContact: emergencyContacts.s2,
    status: "반려",
    requestedAt: addDays(t, -12),
    decidedAt: addDays(t, -11),
    decidedBy: "박기표",
  },
  {
    id: "lr6",
    staffId: "s6",
    type: "반차(오전)",
    startDate: addDays(t, 1),
    endDate: addDays(t, 1),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s6,
    emergencyContact: emergencyContacts.s6,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr7",
    staffId: "s7",
    type: "병가",
    startDate: addDays(t, -3),
    endDate: addDays(t, -2),
    days: 2,
    reason: "몸살감기",
    handoverStaffId: handoverPartners.s7,
    emergencyContact: emergencyContacts.s7,
    status: "승인",
    requestedAt: addDays(t, -3),
    decidedAt: addDays(t, -3),
    decidedBy: "박기표",
  },
  {
    id: "lr8",
    staffId: "s2",
    type: "연차",
    startDate: addDays(t, -80),
    endDate: addDays(t, -76),
    days: 5,
    reason: "여름 휴가",
    handoverStaffId: handoverPartners.s2,
    emergencyContact: emergencyContacts.s2,
    status: "승인",
    requestedAt: addDays(t, -90),
    decidedAt: addDays(t, -89),
    decidedBy: "박기표",
  },
  {
    id: "lr9",
    staffId: "s2",
    type: "연차",
    startDate: addDays(t, -45),
    endDate: addDays(t, -41),
    days: 4.5,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s2,
    emergencyContact: emergencyContacts.s2,
    status: "승인",
    requestedAt: addDays(t, -50),
    decidedAt: addDays(t, -49),
    decidedBy: "박기표",
  },
  {
    id: "lr10",
    staffId: "s4",
    type: "연차",
    startDate: addDays(t, -70),
    endDate: addDays(t, -59),
    days: 10,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s4,
    emergencyContact: emergencyContacts.s4,
    status: "승인",
    requestedAt: addDays(t, -80),
    decidedAt: addDays(t, -79),
    decidedBy: "박기표",
  },
  {
    id: "lr11",
    staffId: "s4",
    type: "연차",
    startDate: addDays(t, -30),
    endDate: addDays(t, -29),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s4,
    emergencyContact: emergencyContacts.s4,
    status: "승인",
    requestedAt: addDays(t, -35),
    decidedAt: addDays(t, -34),
    decidedBy: "박기표",
  },
  {
    id: "lr12",
    staffId: "s6",
    type: "연차",
    startDate: addDays(t, -20),
    endDate: addDays(t, -16),
    days: 4,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s6,
    emergencyContact: emergencyContacts.s6,
    status: "승인",
    requestedAt: addDays(t, -25),
    decidedAt: addDays(t, -24),
    decidedBy: "박기표",
  },
  // 신규 23명(s8~s30)의 휴가 사용 이력
  {
    id: "lr13",
    staffId: "s8",
    type: "연차",
    startDate: addDays(t, -60),
    endDate: addDays(t, -56),
    days: 5,
    reason: "여름 휴가",
    handoverStaffId: handoverPartners.s8,
    emergencyContact: emergencyContacts.s8,
    status: "승인",
    requestedAt: addDays(t, -65),
    decidedAt: addDays(t, -64),
    decidedBy: "박기표",
  },
  {
    id: "lr14",
    staffId: "s9",
    type: "연차",
    startDate: addDays(t, -40),
    endDate: addDays(t, -36),
    days: 5,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s9,
    emergencyContact: emergencyContacts.s9,
    status: "승인",
    requestedAt: addDays(t, -45),
    decidedAt: addDays(t, -44),
    decidedBy: "박기표",
  },
  {
    id: "lr15",
    staffId: "s10",
    type: "연차",
    startDate: addDays(t, -30),
    endDate: addDays(t, -28),
    days: 3,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s10,
    emergencyContact: emergencyContacts.s10,
    status: "승인",
    requestedAt: addDays(t, -35),
    decidedAt: addDays(t, -34),
    decidedBy: "박기표",
  },
  {
    id: "lr16",
    staffId: "s10",
    type: "연차",
    startDate: addDays(t, 5),
    endDate: addDays(t, 6),
    days: 2,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s10,
    emergencyContact: emergencyContacts.s10,
    status: "승인대기",
    requestedAt: addDays(t, -1),
  },
  {
    id: "lr17",
    staffId: "s11",
    type: "병가",
    startDate: addDays(t, -15),
    endDate: addDays(t, -14),
    days: 2,
    reason: "몸살감기",
    handoverStaffId: handoverPartners.s11,
    emergencyContact: emergencyContacts.s11,
    status: "승인",
    requestedAt: addDays(t, -15),
    decidedAt: addDays(t, -15),
    decidedBy: "박기표",
  },
  {
    id: "lr18",
    staffId: "s12",
    type: "연차",
    startDate: addDays(t, -90),
    endDate: addDays(t, -86),
    days: 5,
    reason: "여름 휴가",
    handoverStaffId: handoverPartners.s12,
    emergencyContact: emergencyContacts.s12,
    status: "승인",
    requestedAt: addDays(t, -95),
    decidedAt: addDays(t, -94),
    decidedBy: "박기표",
  },
  {
    id: "lr19",
    staffId: "s13",
    type: "연차",
    startDate: addDays(t, -25),
    endDate: addDays(t, -24),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s13,
    emergencyContact: emergencyContacts.s13,
    status: "승인",
    requestedAt: addDays(t, -30),
    decidedAt: addDays(t, -29),
    decidedBy: "박기표",
  },
  {
    id: "lr20",
    staffId: "s14",
    type: "반차(오전)",
    startDate: addDays(t, -10),
    endDate: addDays(t, -10),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s14,
    emergencyContact: emergencyContacts.s14,
    status: "승인",
    requestedAt: addDays(t, -11),
    decidedAt: addDays(t, -11),
    decidedBy: "박기표",
  },
  {
    id: "lr21",
    staffId: "s15",
    type: "경조사",
    startDate: addDays(t, -50),
    endDate: addDays(t, -48),
    days: 3,
    reason: "가족 경조사",
    handoverStaffId: handoverPartners.s15,
    emergencyContact: emergencyContacts.s15,
    status: "승인",
    requestedAt: addDays(t, -52),
    decidedAt: addDays(t, -51),
    decidedBy: "박기표",
  },
  {
    id: "lr22",
    staffId: "s16",
    type: "연차",
    startDate: addDays(t, -5),
    endDate: addDays(t, -4),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s16,
    emergencyContact: emergencyContacts.s16,
    status: "승인",
    requestedAt: addDays(t, -8),
    decidedAt: addDays(t, -7),
    decidedBy: "박기표",
  },
  {
    id: "lr23",
    staffId: "s16",
    type: "반차(오후)",
    startDate: addDays(t, 2),
    endDate: addDays(t, 2),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s16,
    emergencyContact: emergencyContacts.s16,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr24",
    staffId: "s17",
    type: "반차(오후)",
    startDate: addDays(t, -3),
    endDate: addDays(t, -3),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s17,
    emergencyContact: emergencyContacts.s17,
    status: "승인",
    requestedAt: addDays(t, -4),
    decidedAt: addDays(t, -4),
    decidedBy: "박기표",
  },
  {
    id: "lr25",
    staffId: "s18",
    type: "연차",
    startDate: addDays(t, -20),
    endDate: addDays(t, -19),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s18,
    emergencyContact: emergencyContacts.s18,
    status: "승인",
    requestedAt: addDays(t, -23),
    decidedAt: addDays(t, -22),
    decidedBy: "박기표",
  },
  {
    id: "lr26",
    staffId: "s19",
    type: "병가",
    startDate: addDays(t, -7),
    endDate: addDays(t, -6),
    days: 2,
    reason: "몸살감기",
    handoverStaffId: handoverPartners.s19,
    emergencyContact: emergencyContacts.s19,
    status: "승인",
    requestedAt: addDays(t, -7),
    decidedAt: addDays(t, -7),
    decidedBy: "박기표",
  },
  {
    id: "lr27",
    staffId: "s19",
    type: "반차(오전)",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s19,
    emergencyContact: emergencyContacts.s19,
    status: "승인",
    requestedAt: addDays(t, -1),
    decidedAt: addDays(t, -1),
    decidedBy: "박기표",
  },
  {
    id: "lr28",
    staffId: "s20",
    type: "연차",
    startDate: addDays(t, -2),
    endDate: addDays(t, -2),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s20,
    emergencyContact: emergencyContacts.s20,
    status: "승인",
    requestedAt: addDays(t, -4),
    decidedAt: addDays(t, -3),
    decidedBy: "박기표",
  },
  {
    id: "lr29",
    staffId: "s21",
    type: "반차(오전)",
    startDate: addDays(t, -1),
    endDate: addDays(t, -1),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s21,
    emergencyContact: emergencyContacts.s21,
    status: "승인",
    requestedAt: addDays(t, -2),
    decidedAt: addDays(t, -2),
    decidedBy: "박기표",
  },
  {
    id: "lr30",
    staffId: "s22",
    type: "연차",
    startDate: addDays(t, -35),
    endDate: addDays(t, -33),
    days: 3,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s22,
    emergencyContact: emergencyContacts.s22,
    status: "승인",
    requestedAt: addDays(t, -40),
    decidedAt: addDays(t, -39),
    decidedBy: "박기표",
  },
  {
    id: "lr31",
    staffId: "s23",
    type: "연차",
    startDate: addDays(t, -12),
    endDate: addDays(t, -11),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s23,
    emergencyContact: emergencyContacts.s23,
    status: "승인",
    requestedAt: addDays(t, -15),
    decidedAt: addDays(t, -14),
    decidedBy: "박기표",
  },
  {
    id: "lr32",
    staffId: "s23",
    type: "연차",
    startDate: addDays(t, 10),
    endDate: addDays(t, 12),
    days: 3,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s23,
    emergencyContact: emergencyContacts.s23,
    status: "승인대기",
    requestedAt: addDays(t, -1),
  },
  {
    id: "lr33",
    staffId: "s24",
    type: "반차(오후)",
    startDate: addDays(t, -6),
    endDate: addDays(t, -6),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s24,
    emergencyContact: emergencyContacts.s24,
    status: "승인",
    requestedAt: addDays(t, -7),
    decidedAt: addDays(t, -7),
    decidedBy: "박기표",
  },
  {
    id: "lr34",
    staffId: "s25",
    type: "연차",
    startDate: addDays(t, -18),
    endDate: addDays(t, -18),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s25,
    emergencyContact: emergencyContacts.s25,
    status: "승인",
    requestedAt: addDays(t, -20),
    decidedAt: addDays(t, -19),
    decidedBy: "박기표",
  },
  {
    id: "lr35",
    staffId: "s26",
    type: "병가",
    startDate: addDays(t, -9),
    endDate: addDays(t, -8),
    days: 2,
    reason: "몸살감기",
    handoverStaffId: handoverPartners.s26,
    emergencyContact: emergencyContacts.s26,
    status: "승인",
    requestedAt: addDays(t, -9),
    decidedAt: addDays(t, -9),
    decidedBy: "박기표",
  },
  {
    id: "lr36",
    staffId: "s27",
    type: "반차(오전)",
    startDate: addDays(t, -2),
    endDate: addDays(t, -2),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s27,
    emergencyContact: emergencyContacts.s27,
    status: "승인",
    requestedAt: addDays(t, -3),
    decidedAt: addDays(t, -3),
    decidedBy: "박기표",
  },
  {
    id: "lr37",
    staffId: "s28",
    type: "연차",
    startDate: addDays(t, -40),
    endDate: addDays(t, -39),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s28,
    emergencyContact: emergencyContacts.s28,
    status: "승인",
    requestedAt: addDays(t, -42),
    decidedAt: addDays(t, -41),
    decidedBy: "박기표",
  },
  {
    id: "lr38",
    staffId: "s29",
    type: "반차(오후)",
    startDate: addDays(t, -4),
    endDate: addDays(t, -4),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s29,
    emergencyContact: emergencyContacts.s29,
    status: "승인",
    requestedAt: addDays(t, -5),
    decidedAt: addDays(t, -5),
    decidedBy: "박기표",
  },
  {
    id: "lr39",
    staffId: "s30",
    type: "연차",
    startDate: addDays(t, -25),
    endDate: addDays(t, -24),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s30,
    emergencyContact: emergencyContacts.s30,
    status: "승인",
    requestedAt: addDays(t, -28),
    decidedAt: addDays(t, -27),
    decidedBy: "박기표",
  },
  // 2025-09~2027-02 범위 확장용 추가 휴가 이력 (일괄 생성)
  {
    id: "lr40",
    staffId: "s20",
    type: "연차",
    startDate: addDays(t, -383),
    endDate: addDays(t, -380),
    days: 4,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s20,
    emergencyContact: emergencyContacts.s20,
    status: "승인",
    requestedAt: addDays(t, -387),
    decidedAt: addDays(t, -384),
    decidedBy: "박기표",
  },
  {
    id: "lr41",
    staffId: "s13",
    type: "반차(오후)",
    startDate: addDays(t, -382),
    endDate: addDays(t, -382),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s13,
    emergencyContact: emergencyContacts.s13,
    status: "승인",
    requestedAt: addDays(t, -387),
    decidedAt: addDays(t, -386),
    decidedBy: "박기표",
  },
  {
    id: "lr42",
    staffId: "s12",
    type: "반차(오후)",
    startDate: addDays(t, -380),
    endDate: addDays(t, -380),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s12,
    emergencyContact: emergencyContacts.s12,
    status: "승인",
    requestedAt: addDays(t, -387),
    decidedAt: addDays(t, -386),
    decidedBy: "박기표",
  },
  {
    id: "lr43",
    staffId: "s1",
    type: "연차",
    startDate: addDays(t, -376),
    endDate: addDays(t, -375),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s1,
    emergencyContact: emergencyContacts.s1,
    status: "반려",
    requestedAt: addDays(t, -378),
    decidedAt: addDays(t, -376),
    decidedBy: "박기표",
  },
  {
    id: "lr44",
    staffId: "s5",
    type: "연차",
    startDate: addDays(t, -369),
    endDate: addDays(t, -365),
    days: 5,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s5,
    emergencyContact: emergencyContacts.s5,
    status: "승인",
    requestedAt: addDays(t, -371),
    decidedAt: addDays(t, -369),
    decidedBy: "박기표",
  },
  {
    id: "lr45",
    staffId: "s9",
    type: "반차(오후)",
    startDate: addDays(t, -363),
    endDate: addDays(t, -363),
    days: 0.5,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s9,
    emergencyContact: emergencyContacts.s9,
    status: "승인",
    requestedAt: addDays(t, -373),
    decidedAt: addDays(t, -370),
    decidedBy: "박기표",
  },
  {
    id: "lr46",
    staffId: "s17",
    type: "반차(오전)",
    startDate: addDays(t, -357),
    endDate: addDays(t, -357),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s17,
    emergencyContact: emergencyContacts.s17,
    status: "승인",
    requestedAt: addDays(t, -367),
    decidedAt: addDays(t, -364),
    decidedBy: "박기표",
  },
  {
    id: "lr47",
    staffId: "s15",
    type: "연차",
    startDate: addDays(t, -355),
    endDate: addDays(t, -352),
    days: 4,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s15,
    emergencyContact: emergencyContacts.s15,
    status: "승인",
    requestedAt: addDays(t, -358),
    decidedAt: addDays(t, -355),
    decidedBy: "박기표",
  },
  {
    id: "lr48",
    staffId: "s26",
    type: "반차(오후)",
    startDate: addDays(t, -342),
    endDate: addDays(t, -342),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s26,
    emergencyContact: emergencyContacts.s26,
    status: "승인",
    requestedAt: addDays(t, -352),
    decidedAt: addDays(t, -350),
    decidedBy: "박기표",
  },
  {
    id: "lr49",
    staffId: "s21",
    type: "경조사",
    startDate: addDays(t, -333),
    endDate: addDays(t, -331),
    days: 3,
    reason: "결혼식 참석",
    handoverStaffId: handoverPartners.s21,
    emergencyContact: emergencyContacts.s21,
    status: "승인",
    requestedAt: addDays(t, -341),
    decidedAt: addDays(t, -338),
    decidedBy: "박기표",
  },
  {
    id: "lr50",
    staffId: "s4",
    type: "연차",
    startDate: addDays(t, -330),
    endDate: addDays(t, -330),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s4,
    emergencyContact: emergencyContacts.s4,
    status: "승인",
    requestedAt: addDays(t, -332),
    decidedAt: addDays(t, -331),
    decidedBy: "박기표",
  },
  {
    id: "lr51",
    staffId: "s10",
    type: "연차",
    startDate: addDays(t, -327),
    endDate: addDays(t, -325),
    days: 3,
    reason: "리프레시 휴가",
    handoverStaffId: handoverPartners.s10,
    emergencyContact: emergencyContacts.s10,
    status: "승인",
    requestedAt: addDays(t, -337),
    decidedAt: addDays(t, -336),
    decidedBy: "박기표",
  },
  {
    id: "lr52",
    staffId: "s15",
    type: "연차",
    startDate: addDays(t, -305),
    endDate: addDays(t, -304),
    days: 2,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s15,
    emergencyContact: emergencyContacts.s15,
    status: "승인",
    requestedAt: addDays(t, -315),
    decidedAt: addDays(t, -312),
    decidedBy: "박기표",
  },
  {
    id: "lr53",
    staffId: "s5",
    type: "연차",
    startDate: addDays(t, -298),
    endDate: addDays(t, -297),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s5,
    emergencyContact: emergencyContacts.s5,
    status: "승인",
    requestedAt: addDays(t, -306),
    decidedAt: addDays(t, -303),
    decidedBy: "박기표",
  },
  {
    id: "lr54",
    staffId: "s13",
    type: "연차",
    startDate: addDays(t, -294),
    endDate: addDays(t, -291),
    days: 4,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s13,
    emergencyContact: emergencyContacts.s13,
    status: "승인",
    requestedAt: addDays(t, -304),
    decidedAt: addDays(t, -303),
    decidedBy: "박기표",
  },
  {
    id: "lr55",
    staffId: "s30",
    type: "연차",
    startDate: addDays(t, -289),
    endDate: addDays(t, -287),
    days: 3,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s30,
    emergencyContact: emergencyContacts.s30,
    status: "승인",
    requestedAt: addDays(t, -294),
    decidedAt: addDays(t, -293),
    decidedBy: "박기표",
  },
  {
    id: "lr56",
    staffId: "s14",
    type: "반차(오전)",
    startDate: addDays(t, -287),
    endDate: addDays(t, -287),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s14,
    emergencyContact: emergencyContacts.s14,
    status: "승인",
    requestedAt: addDays(t, -292),
    decidedAt: addDays(t, -289),
    decidedBy: "박기표",
  },
  {
    id: "lr57",
    staffId: "s9",
    type: "연차",
    startDate: addDays(t, -267),
    endDate: addDays(t, -265),
    days: 3,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s9,
    emergencyContact: emergencyContacts.s9,
    status: "승인",
    requestedAt: addDays(t, -277),
    decidedAt: addDays(t, -275),
    decidedBy: "박기표",
  },
  {
    id: "lr58",
    staffId: "s7",
    type: "반차(오전)",
    startDate: addDays(t, -266),
    endDate: addDays(t, -266),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s7,
    emergencyContact: emergencyContacts.s7,
    status: "승인",
    requestedAt: addDays(t, -272),
    decidedAt: addDays(t, -270),
    decidedBy: "박기표",
  },
  {
    id: "lr59",
    staffId: "s23",
    type: "연차",
    startDate: addDays(t, -259),
    endDate: addDays(t, -258),
    days: 2,
    reason: "겨울 휴가",
    handoverStaffId: handoverPartners.s23,
    emergencyContact: emergencyContacts.s23,
    status: "승인",
    requestedAt: addDays(t, -263),
    decidedAt: addDays(t, -261),
    decidedBy: "박기표",
  },
  {
    id: "lr60",
    staffId: "s6",
    type: "연차",
    startDate: addDays(t, -257),
    endDate: addDays(t, -253),
    days: 5,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s6,
    emergencyContact: emergencyContacts.s6,
    status: "승인",
    requestedAt: addDays(t, -267),
    decidedAt: addDays(t, -266),
    decidedBy: "박기표",
  },
  {
    id: "lr61",
    staffId: "s3",
    type: "연차",
    startDate: addDays(t, -233),
    endDate: addDays(t, -232),
    days: 2,
    reason: "겨울 휴가",
    handoverStaffId: handoverPartners.s3,
    emergencyContact: emergencyContacts.s3,
    status: "승인",
    requestedAt: addDays(t, -241),
    decidedAt: addDays(t, -240),
    decidedBy: "박기표",
  },
  {
    id: "lr62",
    staffId: "s17",
    type: "연차",
    startDate: addDays(t, -230),
    endDate: addDays(t, -230),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s17,
    emergencyContact: emergencyContacts.s17,
    status: "승인",
    requestedAt: addDays(t, -234),
    decidedAt: addDays(t, -232),
    decidedBy: "박기표",
  },
  {
    id: "lr63",
    staffId: "s13",
    type: "경조사",
    startDate: addDays(t, -226),
    endDate: addDays(t, -225),
    days: 2,
    reason: "가족 경조사",
    handoverStaffId: handoverPartners.s13,
    emergencyContact: emergencyContacts.s13,
    status: "승인",
    requestedAt: addDays(t, -233),
    decidedAt: addDays(t, -231),
    decidedBy: "박기표",
  },
  {
    id: "lr64",
    staffId: "s3",
    type: "반차(오후)",
    startDate: addDays(t, -225),
    endDate: addDays(t, -225),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s3,
    emergencyContact: emergencyContacts.s3,
    status: "승인",
    requestedAt: addDays(t, -228),
    decidedAt: addDays(t, -225),
    decidedBy: "박기표",
  },
  {
    id: "lr65",
    staffId: "s2",
    type: "연차",
    startDate: addDays(t, -218),
    endDate: addDays(t, -217),
    days: 2,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s2,
    emergencyContact: emergencyContacts.s2,
    status: "승인",
    requestedAt: addDays(t, -225),
    decidedAt: addDays(t, -223),
    decidedBy: "박기표",
  },
  {
    id: "lr66",
    staffId: "s19",
    type: "병가",
    startDate: addDays(t, -218),
    endDate: addDays(t, -217),
    days: 2,
    reason: "치료",
    handoverStaffId: handoverPartners.s19,
    emergencyContact: emergencyContacts.s19,
    status: "승인",
    requestedAt: addDays(t, -225),
    decidedAt: addDays(t, -224),
    decidedBy: "박기표",
  },
  {
    id: "lr67",
    staffId: "s30",
    type: "연차",
    startDate: addDays(t, -209),
    endDate: addDays(t, -209),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s30,
    emergencyContact: emergencyContacts.s30,
    status: "승인",
    requestedAt: addDays(t, -219),
    decidedAt: addDays(t, -216),
    decidedBy: "박기표",
  },
  {
    id: "lr68",
    staffId: "s14",
    type: "반차(오후)",
    startDate: addDays(t, -199),
    endDate: addDays(t, -199),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s14,
    emergencyContact: emergencyContacts.s14,
    status: "승인",
    requestedAt: addDays(t, -207),
    decidedAt: addDays(t, -206),
    decidedBy: "박기표",
  },
  {
    id: "lr69",
    staffId: "s19",
    type: "연차",
    startDate: addDays(t, -193),
    endDate: addDays(t, -192),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s19,
    emergencyContact: emergencyContacts.s19,
    status: "승인",
    requestedAt: addDays(t, -197),
    decidedAt: addDays(t, -195),
    decidedBy: "박기표",
  },
  {
    id: "lr70",
    staffId: "s29",
    type: "경조사",
    startDate: addDays(t, -193),
    endDate: addDays(t, -192),
    days: 2,
    reason: "결혼식 참석",
    handoverStaffId: handoverPartners.s29,
    emergencyContact: emergencyContacts.s29,
    status: "승인",
    requestedAt: addDays(t, -198),
    decidedAt: addDays(t, -197),
    decidedBy: "박기표",
  },
  {
    id: "lr71",
    staffId: "s18",
    type: "연차",
    startDate: addDays(t, -188),
    endDate: addDays(t, -184),
    days: 5,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s18,
    emergencyContact: emergencyContacts.s18,
    status: "반려",
    requestedAt: addDays(t, -196),
    decidedAt: addDays(t, -195),
    decidedBy: "박기표",
  },
  {
    id: "lr72",
    staffId: "s8",
    type: "반차(오전)",
    startDate: addDays(t, -183),
    endDate: addDays(t, -183),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s8,
    emergencyContact: emergencyContacts.s8,
    status: "승인",
    requestedAt: addDays(t, -192),
    decidedAt: addDays(t, -191),
    decidedBy: "박기표",
  },
  {
    id: "lr73",
    staffId: "s28",
    type: "반차(오전)",
    startDate: addDays(t, -183),
    endDate: addDays(t, -183),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s28,
    emergencyContact: emergencyContacts.s28,
    status: "승인",
    requestedAt: addDays(t, -186),
    decidedAt: addDays(t, -185),
    decidedBy: "박기표",
  },
  {
    id: "lr74",
    staffId: "s17",
    type: "연차",
    startDate: addDays(t, -182),
    endDate: addDays(t, -179),
    days: 4,
    reason: "리프레시 휴가",
    handoverStaffId: handoverPartners.s17,
    emergencyContact: emergencyContacts.s17,
    status: "반려",
    requestedAt: addDays(t, -192),
    decidedAt: addDays(t, -189),
    decidedBy: "박기표",
  },
  {
    id: "lr75",
    staffId: "s25",
    type: "연차",
    startDate: addDays(t, -182),
    endDate: addDays(t, -181),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s25,
    emergencyContact: emergencyContacts.s25,
    status: "승인",
    requestedAt: addDays(t, -184),
    decidedAt: addDays(t, -182),
    decidedBy: "박기표",
  },
  {
    id: "lr76",
    staffId: "s10",
    type: "연차",
    startDate: addDays(t, -173),
    endDate: addDays(t, -169),
    days: 5,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s10,
    emergencyContact: emergencyContacts.s10,
    status: "승인",
    requestedAt: addDays(t, -176),
    decidedAt: addDays(t, -175),
    decidedBy: "박기표",
  },
  {
    id: "lr77",
    staffId: "s4",
    type: "반차(오후)",
    startDate: addDays(t, -164),
    endDate: addDays(t, -164),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s4,
    emergencyContact: emergencyContacts.s4,
    status: "승인",
    requestedAt: addDays(t, -171),
    decidedAt: addDays(t, -169),
    decidedBy: "박기표",
  },
  {
    id: "lr78",
    staffId: "s27",
    type: "연차",
    startDate: addDays(t, -162),
    endDate: addDays(t, -161),
    days: 2,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s27,
    emergencyContact: emergencyContacts.s27,
    status: "승인",
    requestedAt: addDays(t, -170),
    decidedAt: addDays(t, -168),
    decidedBy: "박기표",
  },
  {
    id: "lr79",
    staffId: "s3",
    type: "병가",
    startDate: addDays(t, -158),
    endDate: addDays(t, -158),
    days: 1,
    reason: "치료",
    handoverStaffId: handoverPartners.s3,
    emergencyContact: emergencyContacts.s3,
    status: "반려",
    requestedAt: addDays(t, -164),
    decidedAt: addDays(t, -161),
    decidedBy: "박기표",
  },
  {
    id: "lr80",
    staffId: "s8",
    type: "반차(오전)",
    startDate: addDays(t, -151),
    endDate: addDays(t, -151),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s8,
    emergencyContact: emergencyContacts.s8,
    status: "승인",
    requestedAt: addDays(t, -160),
    decidedAt: addDays(t, -159),
    decidedBy: "박기표",
  },
  {
    id: "lr81",
    staffId: "s11",
    type: "반차(오후)",
    startDate: addDays(t, -151),
    endDate: addDays(t, -151),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s11,
    emergencyContact: emergencyContacts.s11,
    status: "승인",
    requestedAt: addDays(t, -154),
    decidedAt: addDays(t, -153),
    decidedBy: "박기표",
  },
  {
    id: "lr82",
    staffId: "s6",
    type: "연차",
    startDate: addDays(t, -149),
    endDate: addDays(t, -145),
    days: 5,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s6,
    emergencyContact: emergencyContacts.s6,
    status: "승인",
    requestedAt: addDays(t, -152),
    decidedAt: addDays(t, -149),
    decidedBy: "박기표",
  },
  {
    id: "lr83",
    staffId: "s11",
    type: "반차(오전)",
    startDate: addDays(t, -140),
    endDate: addDays(t, -140),
    days: 0.5,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s11,
    emergencyContact: emergencyContacts.s11,
    status: "승인",
    requestedAt: addDays(t, -144),
    decidedAt: addDays(t, -142),
    decidedBy: "박기표",
  },
  {
    id: "lr84",
    staffId: "s25",
    type: "경조사",
    startDate: addDays(t, -121),
    endDate: addDays(t, -120),
    days: 2,
    reason: "장례식 참석",
    handoverStaffId: handoverPartners.s25,
    emergencyContact: emergencyContacts.s25,
    status: "승인",
    requestedAt: addDays(t, -131),
    decidedAt: addDays(t, -128),
    decidedBy: "박기표",
  },
  {
    id: "lr85",
    staffId: "s16",
    type: "반차(오후)",
    startDate: addDays(t, -115),
    endDate: addDays(t, -115),
    days: 0.5,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s16,
    emergencyContact: emergencyContacts.s16,
    status: "승인",
    requestedAt: addDays(t, -121),
    decidedAt: addDays(t, -118),
    decidedBy: "박기표",
  },
  {
    id: "lr86",
    staffId: "s22",
    type: "반차(오후)",
    startDate: addDays(t, -111),
    endDate: addDays(t, -111),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s22,
    emergencyContact: emergencyContacts.s22,
    status: "승인",
    requestedAt: addDays(t, -115),
    decidedAt: addDays(t, -113),
    decidedBy: "박기표",
  },
  {
    id: "lr87",
    staffId: "s23",
    type: "경조사",
    startDate: addDays(t, -111),
    endDate: addDays(t, -110),
    days: 2,
    reason: "장례식 참석",
    handoverStaffId: handoverPartners.s23,
    emergencyContact: emergencyContacts.s23,
    status: "승인",
    requestedAt: addDays(t, -114),
    decidedAt: addDays(t, -111),
    decidedBy: "박기표",
  },
  {
    id: "lr88",
    staffId: "s29",
    type: "병가",
    startDate: addDays(t, -106),
    endDate: addDays(t, -105),
    days: 2,
    reason: "몸살감기",
    handoverStaffId: handoverPartners.s29,
    emergencyContact: emergencyContacts.s29,
    status: "승인",
    requestedAt: addDays(t, -114),
    decidedAt: addDays(t, -111),
    decidedBy: "박기표",
  },
  {
    id: "lr89",
    staffId: "s2",
    type: "반차(오전)",
    startDate: addDays(t, -78),
    endDate: addDays(t, -78),
    days: 0.5,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s2,
    emergencyContact: emergencyContacts.s2,
    status: "승인",
    requestedAt: addDays(t, -84),
    decidedAt: addDays(t, -83),
    decidedBy: "박기표",
  },
  {
    id: "lr90",
    staffId: "s7",
    type: "연차",
    startDate: addDays(t, -76),
    endDate: addDays(t, -76),
    days: 1,
    reason: "여름 휴가",
    handoverStaffId: handoverPartners.s7,
    emergencyContact: emergencyContacts.s7,
    status: "반려",
    requestedAt: addDays(t, -82),
    decidedAt: addDays(t, -80),
    decidedBy: "박기표",
  },
  {
    id: "lr91",
    staffId: "s28",
    type: "반차(오전)",
    startDate: addDays(t, -49),
    endDate: addDays(t, -49),
    days: 0.5,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s28,
    emergencyContact: emergencyContacts.s28,
    status: "반려",
    requestedAt: addDays(t, -56),
    decidedAt: addDays(t, -53),
    decidedBy: "박기표",
  },
  {
    id: "lr92",
    staffId: "s27",
    type: "반차(오전)",
    startDate: addDays(t, -12),
    endDate: addDays(t, -12),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s27,
    emergencyContact: emergencyContacts.s27,
    status: "승인",
    requestedAt: addDays(t, -17),
    decidedAt: addDays(t, -15),
    decidedBy: "박기표",
  },
  {
    id: "lr93",
    staffId: "s21",
    type: "반차(오전)",
    startDate: addDays(t, -3),
    endDate: addDays(t, -3),
    days: 0.5,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s21,
    emergencyContact: emergencyContacts.s21,
    status: "승인",
    requestedAt: addDays(t, -6),
    decidedAt: addDays(t, -4),
    decidedBy: "박기표",
  },
  {
    id: "lr94",
    staffId: "s5",
    type: "연차",
    startDate: addDays(t, 24),
    endDate: addDays(t, 28),
    days: 5,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s5,
    emergencyContact: emergencyContacts.s5,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr95",
    staffId: "s26",
    type: "경조사",
    startDate: addDays(t, 27),
    endDate: addDays(t, 29),
    days: 3,
    reason: "결혼식 참석",
    handoverStaffId: handoverPartners.s26,
    emergencyContact: emergencyContacts.s26,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "lr96",
    staffId: "s16",
    type: "연차",
    startDate: addDays(t, 28),
    endDate: addDays(t, 30),
    days: 3,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s16,
    emergencyContact: emergencyContacts.s16,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr97",
    staffId: "s19",
    type: "병가",
    startDate: addDays(t, 46),
    endDate: addDays(t, 46),
    days: 1,
    reason: "몸살감기",
    handoverStaffId: handoverPartners.s19,
    emergencyContact: emergencyContacts.s19,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "lr98",
    staffId: "s12",
    type: "연차",
    startDate: addDays(t, 53),
    endDate: addDays(t, 55),
    days: 3,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s12,
    emergencyContact: emergencyContacts.s12,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "lr99",
    staffId: "s8",
    type: "반차(오후)",
    startDate: addDays(t, 55),
    endDate: addDays(t, 55),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s8,
    emergencyContact: emergencyContacts.s8,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "lr100",
    staffId: "s28",
    type: "연차",
    startDate: addDays(t, 59),
    endDate: addDays(t, 62),
    days: 4,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s28,
    emergencyContact: emergencyContacts.s28,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr101",
    staffId: "s1",
    type: "병가",
    startDate: addDays(t, 60),
    endDate: addDays(t, 61),
    days: 2,
    reason: "치료",
    handoverStaffId: handoverPartners.s1,
    emergencyContact: emergencyContacts.s1,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr102",
    staffId: "s18",
    type: "반차(오후)",
    startDate: addDays(t, 74),
    endDate: addDays(t, 74),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s18,
    emergencyContact: emergencyContacts.s18,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr103",
    staffId: "s22",
    type: "연차",
    startDate: addDays(t, 83),
    endDate: addDays(t, 85),
    days: 3,
    reason: "겨울 휴가",
    handoverStaffId: handoverPartners.s22,
    emergencyContact: emergencyContacts.s22,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "lr104",
    staffId: "s6",
    type: "병가",
    startDate: addDays(t, 96),
    endDate: addDays(t, 96),
    days: 1,
    reason: "몸살감기",
    handoverStaffId: handoverPartners.s6,
    emergencyContact: emergencyContacts.s6,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "lr105",
    staffId: "s16",
    type: "반차(오후)",
    startDate: addDays(t, 100),
    endDate: addDays(t, 100),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s16,
    emergencyContact: emergencyContacts.s16,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr106",
    staffId: "s10",
    type: "연차",
    startDate: addDays(t, 102),
    endDate: addDays(t, 104),
    days: 3,
    reason: "리프레시 휴가",
    handoverStaffId: handoverPartners.s10,
    emergencyContact: emergencyContacts.s10,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "lr107",
    staffId: "s12",
    type: "경조사",
    startDate: addDays(t, 104),
    endDate: addDays(t, 106),
    days: 3,
    reason: "가족 경조사",
    handoverStaffId: handoverPartners.s12,
    emergencyContact: emergencyContacts.s12,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "lr108",
    staffId: "s24",
    type: "연차",
    startDate: addDays(t, 104),
    endDate: addDays(t, 105),
    days: 2,
    reason: "겨울 휴가",
    handoverStaffId: handoverPartners.s24,
    emergencyContact: emergencyContacts.s24,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr109",
    staffId: "s1",
    type: "병가",
    startDate: addDays(t, 114),
    endDate: addDays(t, 114),
    days: 1,
    reason: "몸살감기",
    handoverStaffId: handoverPartners.s1,
    emergencyContact: emergencyContacts.s1,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr110",
    staffId: "s26",
    type: "연차",
    startDate: addDays(t, 119),
    endDate: addDays(t, 122),
    days: 4,
    reason: "가족 여행",
    handoverStaffId: handoverPartners.s26,
    emergencyContact: emergencyContacts.s26,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr111",
    staffId: "s14",
    type: "반차(오후)",
    startDate: addDays(t, 135),
    endDate: addDays(t, 135),
    days: 0.5,
    reason: "병원 진료",
    handoverStaffId: handoverPartners.s14,
    emergencyContact: emergencyContacts.s14,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "lr112",
    staffId: "s11",
    type: "연차",
    startDate: addDays(t, 137),
    endDate: addDays(t, 139),
    days: 3,
    reason: "리프레시 휴가",
    handoverStaffId: handoverPartners.s11,
    emergencyContact: emergencyContacts.s11,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "lr113",
    staffId: "s20",
    type: "반차(오후)",
    startDate: addDays(t, 140),
    endDate: addDays(t, 140),
    days: 0.5,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s20,
    emergencyContact: emergencyContacts.s20,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr114",
    staffId: "s24",
    type: "연차",
    startDate: addDays(t, 141),
    endDate: addDays(t, 142),
    days: 2,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s24,
    emergencyContact: emergencyContacts.s24,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr115",
    staffId: "s29",
    type: "연차",
    startDate: addDays(t, 145),
    endDate: addDays(t, 149),
    days: 5,
    reason: "리프레시 휴가",
    handoverStaffId: handoverPartners.s29,
    emergencyContact: emergencyContacts.s29,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "lr116",
    staffId: "s27",
    type: "연차",
    startDate: addDays(t, 152),
    endDate: addDays(t, 152),
    days: 1,
    reason: "개인 사유",
    handoverStaffId: handoverPartners.s27,
    emergencyContact: emergencyContacts.s27,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "lr117",
    staffId: "s18",
    type: "반차(오전)",
    startDate: addDays(t, 158),
    endDate: addDays(t, 158),
    days: 0.5,
    reason: "관공서 방문",
    handoverStaffId: handoverPartners.s18,
    emergencyContact: emergencyContacts.s18,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
];

export const initialTripRecords: TripRecord[] = [
  {
    id: "tr1",
    staffId: "s1",
    type: "출장",
    startDate: addDays(t, 2),
    endDate: addDays(t, 3),
    purpose: "대전 협력사 미팅",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr2",
    staffId: "s2",
    type: "외출",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    startTime: "14:00",
    endTime: "16:00",
    purpose: "은행 업무",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr3",
    staffId: "s6",
    type: "외출",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    startTime: "10:30",
    endTime: "11:30",
    purpose: "병원 진료",
    reachable: false,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  // 신규 23명(s8~s30)의 출장·외출
  {
    id: "tr4",
    staffId: "s8",
    type: "출장",
    startDate: addDays(t, 3),
    endDate: addDays(t, 4),
    purpose: "본사 임원 회의",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -1),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr5",
    staffId: "s13",
    type: "외출",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    startTime: "11:00",
    endTime: "12:00",
    purpose: "거래처 미팅",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr6",
    staffId: "s17",
    type: "외출",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    startTime: "15:00",
    endTime: "16:30",
    purpose: "은행 업무",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr7",
    staffId: "s24",
    type: "출장",
    startDate: addDays(t, 1),
    endDate: addDays(t, 2),
    purpose: "지방 협력사 방문",
    reachable: false,
    status: "승인",
    requestedAt: addDays(t, -1),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr8",
    staffId: "s20",
    type: "외출",
    startDate: addDays(t, 0),
    endDate: addDays(t, 0),
    startTime: "13:30",
    endTime: "14:30",
    purpose: "병원 진료",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  // 2025-09~2027-02 범위 확장용 추가 출장·외출 이력 (일괄 생성)
  {
    id: "tr9",
    staffId: "s20",
    type: "출장",
    startDate: addDays(t, -381),
    endDate: addDays(t, -380),
    purpose: "대전 협력사 미팅",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -381),
    decidedAt: addDays(t, -381),
    decidedBy: "박기표",
  },
  {
    id: "tr10",
    staffId: "s23",
    type: "외출",
    startDate: addDays(t, -353),
    endDate: addDays(t, -353),
    startTime: "12:00",
    endTime: "14:30",
    purpose: "병원 진료",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -353),
    decidedAt: addDays(t, -353),
    decidedBy: "박기표",
  },
  {
    id: "tr11",
    staffId: "s24",
    type: "출장",
    startDate: addDays(t, -327),
    endDate: addDays(t, -325),
    purpose: "본사 임원 회의",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -329),
    decidedAt: addDays(t, -327),
    decidedBy: "박기표",
  },
  {
    id: "tr12",
    staffId: "s30",
    type: "출장",
    startDate: addDays(t, -318),
    endDate: addDays(t, -317),
    purpose: "세미나 참석",
    reachable: false,
    status: "승인",
    requestedAt: addDays(t, -320),
    decidedAt: addDays(t, -319),
    decidedBy: "박기표",
  },
  {
    id: "tr13",
    staffId: "s15",
    type: "외출",
    startDate: addDays(t, -282),
    endDate: addDays(t, -282),
    startTime: "09:00",
    endTime: "10:00",
    purpose: "병원 진료",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -282),
    decidedAt: addDays(t, -282),
    decidedBy: "박기표",
  },
  {
    id: "tr14",
    staffId: "s26",
    type: "외출",
    startDate: addDays(t, -282),
    endDate: addDays(t, -282),
    startTime: "14:00",
    endTime: "15:30",
    purpose: "외부 교육",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -282),
    decidedAt: addDays(t, -282),
    decidedBy: "박기표",
  },
  {
    id: "tr15",
    staffId: "s28",
    type: "출장",
    startDate: addDays(t, -275),
    endDate: addDays(t, -273),
    purpose: "고객사 방문",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -275),
    decidedAt: addDays(t, -275),
    decidedBy: "박기표",
  },
  {
    id: "tr16",
    staffId: "s17",
    type: "외출",
    startDate: addDays(t, -273),
    endDate: addDays(t, -273),
    startTime: "11:30",
    endTime: "12:00",
    purpose: "외부 교육",
    reachable: true,
    status: "반려",
    requestedAt: addDays(t, -276),
    decidedAt: addDays(t, -275),
    decidedBy: "박기표",
  },
  {
    id: "tr17",
    staffId: "s2",
    type: "외출",
    startDate: addDays(t, -271),
    endDate: addDays(t, -271),
    startTime: "13:30",
    endTime: "15:00",
    purpose: "외부 교육",
    reachable: true,
    status: "반려",
    requestedAt: addDays(t, -272),
    decidedAt: addDays(t, -271),
    decidedBy: "박기표",
  },
  {
    id: "tr18",
    staffId: "s3",
    type: "외출",
    startDate: addDays(t, -236),
    endDate: addDays(t, -236),
    startTime: "13:00",
    endTime: "14:00",
    purpose: "관공서 방문",
    reachable: false,
    status: "승인",
    requestedAt: addDays(t, -237),
    decidedAt: addDays(t, -236),
    decidedBy: "박기표",
  },
  {
    id: "tr19",
    staffId: "s10",
    type: "출장",
    startDate: addDays(t, -215),
    endDate: addDays(t, -215),
    purpose: "본사 임원 회의",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -216),
    decidedAt: addDays(t, -215),
    decidedBy: "박기표",
  },
  {
    id: "tr20",
    staffId: "s26",
    type: "외출",
    startDate: addDays(t, -212),
    endDate: addDays(t, -212),
    startTime: "16:30",
    endTime: "17:00",
    purpose: "관공서 방문",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -213),
    decidedAt: addDays(t, -212),
    decidedBy: "박기표",
  },
  {
    id: "tr21",
    staffId: "s13",
    type: "외출",
    startDate: addDays(t, -211),
    endDate: addDays(t, -211),
    startTime: "14:00",
    endTime: "16:00",
    purpose: "외부 교육",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -211),
    decidedAt: addDays(t, -211),
    decidedBy: "박기표",
  },
  {
    id: "tr22",
    staffId: "s4",
    type: "출장",
    startDate: addDays(t, -196),
    endDate: addDays(t, -194),
    purpose: "현장 점검",
    reachable: true,
    status: "반려",
    requestedAt: addDays(t, -196),
    decidedAt: addDays(t, -196),
    decidedBy: "박기표",
  },
  {
    id: "tr23",
    staffId: "s16",
    type: "외출",
    startDate: addDays(t, -189),
    endDate: addDays(t, -189),
    startTime: "11:30",
    endTime: "13:00",
    purpose: "거래처 미팅",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -192),
    decidedAt: addDays(t, -191),
    decidedBy: "박기표",
  },
  {
    id: "tr24",
    staffId: "s2",
    type: "출장",
    startDate: addDays(t, -160),
    endDate: addDays(t, -159),
    purpose: "대전 협력사 미팅",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -162),
    decidedAt: addDays(t, -160),
    decidedBy: "박기표",
  },
  {
    id: "tr25",
    staffId: "s8",
    type: "외출",
    startDate: addDays(t, -135),
    endDate: addDays(t, -135),
    startTime: "16:30",
    endTime: "17:30",
    purpose: "외부 교육",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -135),
    decidedAt: addDays(t, -135),
    decidedBy: "박기표",
  },
  {
    id: "tr26",
    staffId: "s18",
    type: "외출",
    startDate: addDays(t, -126),
    endDate: addDays(t, -126),
    startTime: "12:30",
    endTime: "13:30",
    purpose: "병원 진료",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -126),
    decidedAt: addDays(t, -126),
    decidedBy: "박기표",
  },
  {
    id: "tr27",
    staffId: "s1",
    type: "외출",
    startDate: addDays(t, -108),
    endDate: addDays(t, -108),
    startTime: "11:00",
    endTime: "12:30",
    purpose: "병원 진료",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -111),
    decidedAt: addDays(t, -110),
    decidedBy: "박기표",
  },
  {
    id: "tr28",
    staffId: "s27",
    type: "출장",
    startDate: addDays(t, -80),
    endDate: addDays(t, -80),
    purpose: "고객사 방문",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -83),
    decidedAt: addDays(t, -81),
    decidedBy: "박기표",
  },
  {
    id: "tr29",
    staffId: "s4",
    type: "외출",
    startDate: addDays(t, -72),
    endDate: addDays(t, -72),
    startTime: "10:00",
    endTime: "11:00",
    purpose: "병원 진료",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -75),
    decidedAt: addDays(t, -72),
    decidedBy: "박기표",
  },
  {
    id: "tr30",
    staffId: "s12",
    type: "외출",
    startDate: addDays(t, -28),
    endDate: addDays(t, -28),
    startTime: "13:30",
    endTime: "14:30",
    purpose: "관공서 방문",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, -28),
    decidedAt: addDays(t, -28),
    decidedBy: "박기표",
  },
  {
    id: "tr31",
    staffId: "s15",
    type: "출장",
    startDate: addDays(t, 37),
    endDate: addDays(t, 39),
    purpose: "세미나 참석",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr32",
    staffId: "s1",
    type: "외출",
    startDate: addDays(t, 39),
    endDate: addDays(t, 39),
    startTime: "10:00",
    endTime: "11:00",
    purpose: "거래처 미팅",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr33",
    staffId: "s8",
    type: "외출",
    startDate: addDays(t, 48),
    endDate: addDays(t, 48),
    startTime: "10:00",
    endTime: "12:00",
    purpose: "관공서 방문",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr34",
    staffId: "s11",
    type: "출장",
    startDate: addDays(t, 57),
    endDate: addDays(t, 58),
    purpose: "고객사 방문",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr35",
    staffId: "s10",
    type: "외출",
    startDate: addDays(t, 62),
    endDate: addDays(t, 62),
    startTime: "16:00",
    endTime: "17:30",
    purpose: "외부 교육",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr36",
    staffId: "s18",
    type: "출장",
    startDate: addDays(t, 64),
    endDate: addDays(t, 64),
    purpose: "세미나 참석",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr37",
    staffId: "s21",
    type: "외출",
    startDate: addDays(t, 67),
    endDate: addDays(t, 67),
    startTime: "14:30",
    endTime: "15:30",
    purpose: "거래처 미팅",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr38",
    staffId: "s13",
    type: "출장",
    startDate: addDays(t, 100),
    endDate: addDays(t, 100),
    purpose: "대전 협력사 미팅",
    reachable: true,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
  {
    id: "tr39",
    staffId: "s29",
    type: "출장",
    startDate: addDays(t, 105),
    endDate: addDays(t, 105),
    purpose: "본사 임원 회의",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr40",
    staffId: "s27",
    type: "외출",
    startDate: addDays(t, 111),
    endDate: addDays(t, 111),
    startTime: "10:30",
    endTime: "12:00",
    purpose: "관공서 방문",
    reachable: true,
    status: "승인",
    requestedAt: addDays(t, 0),
    decidedAt: addDays(t, 0),
    decidedBy: "박기표",
  },
  {
    id: "tr41",
    staffId: "s24",
    type: "외출",
    startDate: addDays(t, 117),
    endDate: addDays(t, 117),
    startTime: "10:30",
    endTime: "12:00",
    purpose: "거래처 미팅",
    reachable: true,
    status: "승인대기",
    requestedAt: addDays(t, 0),
  },
];

// 연차 사용 촉진(근로기준법 제61조) 진행 상태 시드 — 1차 촉구/근로자
// 응답/2차 통보의 각 단계를 골고루 보여주기 위한 예시 데이터. 목록에
// 없는 나머지 직원은 아직 1차 촉구를 보내지 않은 상태(1차대상)로
// 표시된다.
// 연차 사용 촉진(근로기준법 제61조) 진행 상태 시드 — 30명 중 대부분은
// 이미 1차 촉구를 보내고 근로자 응답(또는 2차 통보)까지 마친 상태로
// 구성하고, 일부만 실제로 조치가 필요한 상태(근로자 응답 대기, 2차
// 대상, 1차 촉구 누락)로 남겨서 "조치 필요" 인원이 소수로 나오도록
// 했다 — 매년 꾸준히 챙겨온 회사를 가정한 값이다. 목록에 없는
// 직원(s6, s17)은 1차 촉구 자체를 아직 보내지 않은 상태(1차대상)다.
export const initialLeavePromotionNotices: LeavePromotionNotice[] = [
  {
    staffId: "s27",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-04`,
    firstNoticeDays: 8,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-05`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-25`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-27`,
  },
  {
    staffId: "s20",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-05`,
    firstNoticeDays: 12,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-14`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-21`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-22`,
  },
  {
    staffId: "s18",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-04`,
    firstNoticeDays: 19,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-05`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-17`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-19`,
  },
  {
    staffId: "s19",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-05`,
    firstNoticeDays: 10,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-11`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-19`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-21`,
  },
  {
    staffId: "s21",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-03`,
    firstNoticeDays: 13,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-08`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-25`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-26`,
  },
  {
    staffId: "s29",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-03`,
    firstNoticeDays: 7,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-09`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-23`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-24`,
  },
  {
    staffId: "s8",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-09`,
    firstNoticeDays: 12,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-12`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-17`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-19`,
  },
  {
    staffId: "s9",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-08`,
    firstNoticeDays: 11,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-13`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-18`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-19`,
  },
  {
    staffId: "s22",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-03`,
    firstNoticeDays: 17,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-05`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-21`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-22`,
  },
  {
    staffId: "s5",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-04`,
    firstNoticeDays: 13,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-13`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-19`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-21`,
  },
  {
    staffId: "s11",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-03`,
    firstNoticeDays: 5,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-11`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-20`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-21`,
  },
  {
    staffId: "s23",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-01`,
    firstNoticeDays: 8,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-09`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-15`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-16`,
  },
  {
    staffId: "s28",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-03`,
    firstNoticeDays: 5,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-10`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-20`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-21`,
  },
  {
    staffId: "s15",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-06`,
    firstNoticeDays: 7,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-10`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-23`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-25`,
  },
  {
    staffId: "s12",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-09`,
    firstNoticeDays: 8,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-15`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-16`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-18`,
  },
  {
    staffId: "s3",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-04`,
    firstNoticeDays: 13,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-10`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-24`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-25`,
  },
  {
    staffId: "s4",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-06`,
    firstNoticeDays: 14,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-11`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-18`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-19`,
  },
  {
    staffId: "s1",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-05`,
    firstNoticeDays: 17,
    employeeSpecifiedAt: `${CURRENT_YEAR}-07-10`,
    employeeSpecifiedStart: `${CURRENT_YEAR}-12-22`,
    employeeSpecifiedEnd: `${CURRENT_YEAR}-12-23`,
  },
  {
    staffId: "s30",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-08`,
    firstNoticeDays: 8,
    secondNoticeAt: `${CURRENT_YEAR}-09-18`,
    secondNoticeStart: `${CURRENT_YEAR}-12-17`,
    secondNoticeEnd: `${CURRENT_YEAR}-12-19`,
  },
  {
    staffId: "s26",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-04`,
    firstNoticeDays: 13,
    secondNoticeAt: `${CURRENT_YEAR}-09-14`,
    secondNoticeStart: `${CURRENT_YEAR}-12-23`,
    secondNoticeEnd: `${CURRENT_YEAR}-12-24`,
  },
  {
    staffId: "s16",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-05`,
    firstNoticeDays: 18,
    secondNoticeAt: `${CURRENT_YEAR}-09-10`,
    secondNoticeStart: `${CURRENT_YEAR}-12-24`,
    secondNoticeEnd: `${CURRENT_YEAR}-12-26`,
  },
  {
    staffId: "s7",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-03`,
    firstNoticeDays: 16,
    secondNoticeAt: `${CURRENT_YEAR}-08-13`,
    secondNoticeStart: `${CURRENT_YEAR}-12-22`,
    secondNoticeEnd: `${CURRENT_YEAR}-12-24`,
  },
  {
    staffId: "s2",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-03`,
    firstNoticeDays: 17,
    secondNoticeAt: `${CURRENT_YEAR}-09-09`,
    secondNoticeStart: `${CURRENT_YEAR}-12-23`,
    secondNoticeEnd: `${CURRENT_YEAR}-12-24`,
  },
  {
    staffId: "s10",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-09-20`,
    firstNoticeDays: 7,
  },
  {
    staffId: "s25",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-09-16`,
    firstNoticeDays: 17,
  },
  {
    staffId: "s14",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-06`,
    firstNoticeDays: 6,
  },
  {
    staffId: "s13",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-07`,
    firstNoticeDays: 8,
  },
  {
    staffId: "s24",
    year: CURRENT_YEAR,
    firstNoticeAt: `${CURRENT_YEAR}-07-05`,
    firstNoticeDays: 20,
  },
];
