import type { Candidate } from "./recruit-types";
import { addDays, today } from "./date";

const t = today();

export const seedCandidates: Candidate[] = [
  {
    id: "cand-seed-1",
    createdAt: new Date(addDays(t, -3)).toISOString(),
    name: "오세훈",
    birthYear: "2001",
    phone: "010-2345-6789",
    email: "shoh@example.com",
    region: "서울",
    desiredRole: "인사/총무",
    portfolioUrl: "",
    desiredSalary: "3,200만원",
    educationLevel: "대졸",
    schoolName: "다온대학교",
    major: "경영학",
    graduationDate: "2026-02",
    gpa: "3.7 / 4.5",
    languageScore: "토익 820",
    militaryStatus: "군필",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "",
    previousSalary: "",
    certifications: ["컴퓨터활용능력"],
    skills: ["Excel", "PowerPoint", "Notion"],
    excelLevel: 3,
    englishLevel: null,
    workType: "정규직",
    mainTasks:
      "학과 학생회 인사팀에서 신입생 오리엔테이션 인원 150명의 조 편성과 일정 관리를 맡아, 엑셀로 배정표를 만들어 처리 시간을 줄였어요.",
    previousExperience: "",
    selfIntroduction:
      "사람과 조직의 관계에 관심이 많아 인사 직무에 지원했어요. 데이터로 채용과 조직문화를 개선하는 실무자가 되고 싶어요.",
    availableStartDate: "2026-11-01",
    applicationSource: "채용사이트",
    evaluationGrade: "",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "서류",
  },
  {
    id: "cand-seed-2",
    createdAt: new Date(addDays(t, -2)).toISOString(),
    name: "백하윤",
    birthYear: "1994",
    phone: "010-3456-7890",
    email: "hybaek@example.com",
    region: "경기",
    desiredRole: "인사/총무",
    portfolioUrl: "https://example.com/hayoon-baek",
    desiredSalary: "4,500만원",
    educationLevel: "대졸",
    schoolName: "은강대학교",
    major: "심리학",
    graduationDate: "2018-02",
    gpa: "",
    languageScore: "토익스피킹 IH",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "3~5년",
    employmentStatus: "재직중",
    recentCompany: "예시물산",
    department: "인사팀",
    position: "대리",
    joinDate: "2021-05-10",
    salaryNegotiable: "가능",
    previousSalary: "4,200만원",
    certifications: ["정보처리기사", "사회조사분석사"],
    skills: ["Excel", "SQL", "Notion", "Slack"],
    excelLevel: 4,
    englishLevel: null,
    workType: "정규직",
    mainTasks:
      "연간 인사평가 프로세스를 담당했고, 평가 데이터를 SQL로 정리해 부서별 리포트 작성 시간을 절반으로 줄였어요. 신입 온보딩 체크리스트를 새로 설계해 담당 부서 문의를 줄였어요.",
    previousExperience: "첫 직장에서 2년간 총무 업무를 담당하며 사내 행사와 비품 관리를 맡았어요.",
    selfIntroduction:
      "제도를 설계하는 데서 그치지 않고 실제로 잘 쓰이는지 확인하는 걸 중요하게 생각해요. 이직을 통해 더 큰 조직의 인사 체계를 경험해보고 싶어요.",
    availableStartDate: "2026-12-15",
    applicationSource: "지인 추천",
    evaluationGrade: "A",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "면접",
  },
  {
    id: "cand-seed-3",
    createdAt: new Date(addDays(t, -1)).toISOString(),
    name: "남궁태윤",
    birthYear: "1986",
    phone: "010-4567-8901",
    email: "tynam@example.com",
    region: "인천",
    desiredRole: "인사/총무",
    portfolioUrl: "",
    desiredSalary: "7,000만원",
    educationLevel: "석사",
    schoolName: "한백대학교",
    major: "경영학(인사조직 전공)",
    graduationDate: "2013-08",
    gpa: "",
    languageScore: "",
    militaryStatus: "군필",
    veteranStatus: "해당없음",
    totalExperience: "10년 이상",
    employmentStatus: "재직중",
    recentCompany: "예시테크",
    department: "인사기획팀",
    position: "차장",
    joinDate: "2016-03-02",
    salaryNegotiable: "협의 필요",
    previousSalary: "6,800만원",
    certifications: ["없음"],
    skills: ["Excel", "PowerPoint", "Notion"],
    excelLevel: 5,
    englishLevel: null,
    workType: "정규직",
    mainTasks:
      "조직개편 3회를 주도했고, 연 200명 규모 채용 프로세스를 총괄했어요. 이직률을 낮추기 위한 온보딩 개편으로 1년 내 퇴사율을 낮췄어요.",
    previousExperience: "첫 직장에서 5년간 인사 실무를 담당하며 급여와 4대보험 업무를 처리했어요.",
    selfIntroduction:
      "실무자에서 관리자로 성장하며 사람에 대한 판단과 제도 설계 양쪽을 다뤄왔어요. 조직의 성장 단계에 맞는 인사 체계를 만드는 역할을 계속하고 싶어요.",
    availableStartDate: "2027-01-01",
    applicationSource: "기타",
    evaluationGrade: "S",
    recruiterInCharge: "정하은",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "합격",
  },
];
