import type { Candidate } from "./recruit-types";
import { addDays, today } from "./date";

const t = today();

// 신입 15명(전원 무직) + 경력직 15명, 총 30명. 신입은 재직 이력이 없으므로
// employmentStatus를 항상 "무직"으로 고정한다.
//
// 면접 단계인 지원자 중 한 명(cand-seed-2)은 "오늘 면접"으로 항상
// 재고정되도록 PINNED_TODAY_INTERVIEW_IDS에 등록한다 — 그 외 면접 일정은
// 생성 시점(오늘) 기준으로 흩어져 있어 시간이 지나면 자연히 과거로 밀려난다.
export const PINNED_TODAY_INTERVIEW_IDS = new Set(["cand-seed-2"]);

export const seedCandidates: Candidate[] = [
  {
    id: "cand-seed-1",
    createdAt: new Date(addDays(t, -14)).toISOString(),
    name: "서연건",
    birthYear: "1999",
    phone: "010-2000-3000",
    email: "c1@example.com",
    region: "세종",
    desiredRole: "영업",
    portfolioUrl: "",
    desiredSalary: "3,100만원",
    educationLevel: "대졸",
    schoolName: "이음대학교",
    major: "전자공학",
    graduationDate: "2026-08",
    gpa: "",
    languageScore: "",
    militaryStatus: "면제",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "협의 필요",
    previousSalary: "",
    certifications: ["한국사능력검정", "정보처리기사"],
    skills: ["Word", "SQL"],
    aiLevel: 5,
    englishLevel: 3,
    workType: "정규직",
    mainTasks: "학과 학생회에서 행사 기획과 예산 관리를 맡아 200명 규모 행사를 문제없이 운영했어요.",
    previousExperience: "",
    selfIntroduction: "새로운 환경에 빠르게 적응하는 편이고, 데이터를 근거로 판단하는 습관을 기르고 있습니다.",
    availableStartDate: "2026-12-17",
    applicationSource: "채용사이트",
    evaluationGrade: "B",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "최종",
  },
  {
    id: "cand-seed-2",
    createdAt: new Date(addDays(t, -9)).toISOString(),
    name: "조준호",
    birthYear: "2001",
    phone: "010-2037-3053",
    email: "c2@example.com",
    region: "충남",
    desiredRole: "고객지원",
    portfolioUrl: "https://example.com/cand-seed-2",
    desiredSalary: "3,400만원",
    educationLevel: "전문대졸",
    schoolName: "해솔대학교",
    major: "전자공학",
    graduationDate: "2024-08",
    gpa: "3.8 / 4.5",
    languageScore: "토익 904",
    militaryStatus: "미필",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "가능",
    previousSalary: "",
    certifications: ["한국사능력검정", "전산회계"],
    skills: ["PowerPoint", "Notion"],
    aiLevel: 2,
    englishLevel: 3,
    workType: "정규직",
    mainTasks: "인턴십 기간 동안 데이터 정리와 보고서 작성을 지원하며 실무 툴 사용법을 익혔어요.",
    previousExperience: "",
    selfIntroduction: "배운 것을 실무에 바로 적용하고 싶어 지원했습니다. 꼼꼼함과 책임감을 강점으로 생각합니다.",
    availableStartDate: "2026-11-09",
    applicationSource: "채용사이트",
    evaluationGrade: "B",
    recruiterInCharge: "박지훈",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "면접",
    interviewAt: `${addDays(t, 0)}T09:30`,
  },
  {
    id: "cand-seed-3",
    createdAt: new Date(addDays(t, -2)).toISOString(),
    name: "최민호",
    birthYear: "2003",
    phone: "010-2074-3106",
    email: "c3@example.com",
    region: "부산",
    desiredRole: "개발",
    portfolioUrl: "",
    desiredSalary: "3,400만원",
    educationLevel: "대졸",
    schoolName: "청람대학교",
    major: "경영학",
    graduationDate: "2024-02",
    gpa: "",
    languageScore: "",
    militaryStatus: "비대상",
    veteranStatus: "해당",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "가능",
    previousSalary: "",
    certifications: ["정보처리기사"],
    skills: ["PowerPoint", "SQL", "Excel"],
    aiLevel: 2,
    englishLevel: 3,
    workType: "인턴",
    mainTasks: "학과 학생회에서 행사 기획과 예산 관리를 맡아 200명 규모 행사를 문제없이 운영했어요.",
    previousExperience: "",
    selfIntroduction: "새로운 환경에 빠르게 적응하는 편이고, 데이터를 근거로 판단하는 습관을 기르고 있습니다.",
    availableStartDate: "2026-11-07",
    applicationSource: "헤드헌터",
    evaluationGrade: "B",
    recruiterInCharge: "박지훈",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: true,
    addToTalentPool: true,
    stage: "최종",
  },
  {
    id: "cand-seed-4",
    createdAt: new Date(addDays(t, -38)).toISOString(),
    name: "백윤결",
    birthYear: "2001",
    phone: "010-2111-3159",
    email: "c4@example.com",
    region: "강원",
    desiredRole: "디자인",
    portfolioUrl: "",
    desiredSalary: "3,400만원",
    educationLevel: "석사",
    schoolName: "서라벌대학교",
    major: "광고홍보학",
    graduationDate: "2025-08",
    gpa: "3.7 / 4.5",
    languageScore: "토익 650",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "가능",
    previousSalary: "",
    certifications: ["한국사능력검정", "컴퓨터활용능력"],
    skills: ["SQL", "PowerPoint"],
    aiLevel: null,
    englishLevel: 2,
    workType: "정규직",
    mainTasks: "동아리 운영진으로 신입 부원 모집과 SNS 콘텐츠 제작을 맡아 팔로워를 두 배로 늘렸어요.",
    previousExperience: "",
    selfIntroduction: "새로운 환경에 빠르게 적응하는 편이고, 데이터를 근거로 판단하는 습관을 기르고 있습니다.",
    availableStartDate: "2026-11-24",
    applicationSource: "지인 추천",
    evaluationGrade: "A",
    recruiterInCharge: "정하은",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "합격",
  },
  {
    id: "cand-seed-5",
    createdAt: new Date(addDays(t, -16)).toISOString(),
    name: "한민솔",
    birthYear: "2003",
    phone: "010-2148-3212",
    email: "c5@example.com",
    region: "충남",
    desiredRole: "마케팅",
    portfolioUrl: "",
    desiredSalary: "3,000만원",
    educationLevel: "석사",
    schoolName: "은강대학교",
    major: "시각디자인학",
    graduationDate: "2024-02",
    gpa: "3.7 / 4.5",
    languageScore: "",
    militaryStatus: "면제",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "협의 필요",
    previousSalary: "",
    certifications: ["없음"],
    skills: ["SQL", "Word", "Notion", "PowerPoint"],
    aiLevel: 2,
    englishLevel: null,
    workType: "정규직",
    mainTasks: "인턴십 기간 동안 데이터 정리와 보고서 작성을 지원하며 실무 툴 사용법을 익혔어요.",
    previousExperience: "",
    selfIntroduction: "배운 것을 실무에 바로 적용하고 싶어 지원했습니다. 꼼꼼함과 책임감을 강점으로 생각합니다.",
    availableStartDate: "2026-11-23",
    applicationSource: "회사 홈페이지",
    evaluationGrade: "C",
    recruiterInCharge: "정하은",
    consentPrivacy: true,
    consentThirdParty: true,
    consentMarketing: true,
    addToTalentPool: false,
    stage: "면접",
    interviewAt: `${addDays(t, -1)}T13:30`,
  },
  {
    id: "cand-seed-6",
    createdAt: new Date(addDays(t, -26)).toISOString(),
    name: "최지성",
    birthYear: "2001",
    phone: "010-2185-3265",
    email: "c6@example.com",
    region: "대구",
    desiredRole: "디자인",
    portfolioUrl: "",
    desiredSalary: "2,800만원",
    educationLevel: "석사",
    schoolName: "청람대학교",
    major: "국어국문학",
    graduationDate: "2024-02",
    gpa: "",
    languageScore: "토익 829",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "가능",
    previousSalary: "",
    certifications: ["전산회계", "MOS"],
    skills: ["Excel", "Slack", "Notion"],
    aiLevel: 2,
    englishLevel: 1,
    workType: "정규직",
    mainTasks: "동아리 운영진으로 신입 부원 모집과 SNS 콘텐츠 제작을 맡아 팔로워를 두 배로 늘렸어요.",
    previousExperience: "",
    selfIntroduction: "배운 것을 실무에 바로 적용하고 싶어 지원했습니다. 꼼꼼함과 책임감을 강점으로 생각합니다.",
    availableStartDate: "2026-12-18",
    applicationSource: "기타",
    evaluationGrade: "",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: true,
    stage: "서류",
  },
  {
    id: "cand-seed-7",
    createdAt: new Date(addDays(t, -45)).toISOString(),
    name: "한서율",
    birthYear: "2003",
    phone: "010-2222-3318",
    email: "c7@example.com",
    region: "세종",
    desiredRole: "인사/총무",
    portfolioUrl: "",
    desiredSalary: "2,800만원",
    educationLevel: "석사",
    schoolName: "은강대학교",
    major: "디자인학",
    graduationDate: "2025-02",
    gpa: "",
    languageScore: "토익 893",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "협의 필요",
    previousSalary: "",
    certifications: ["MOS"],
    skills: ["SQL", "Slack", "Excel"],
    aiLevel: 3,
    englishLevel: 1,
    workType: "정규직",
    mainTasks: "동아리 운영진으로 신입 부원 모집과 SNS 콘텐츠 제작을 맡아 팔로워를 두 배로 늘렸어요.",
    previousExperience: "",
    selfIntroduction: "배운 것을 실무에 바로 적용하고 싶어 지원했습니다. 꼼꼼함과 책임감을 강점으로 생각합니다.",
    availableStartDate: "2026-11-15",
    applicationSource: "회사 홈페이지",
    evaluationGrade: "B",
    recruiterInCharge: "정하은",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: true,
    stage: "면접",
    interviewAt: `${addDays(t, 0)}T16:00`,
  },
  {
    id: "cand-seed-8",
    createdAt: new Date(addDays(t, -26)).toISOString(),
    name: "홍하훈",
    birthYear: "2000",
    phone: "010-2259-3371",
    email: "c8@example.com",
    region: "경남",
    desiredRole: "기타",
    portfolioUrl: "",
    desiredSalary: "3,400만원",
    educationLevel: "전문대졸",
    schoolName: "청람대학교",
    major: "행정학",
    graduationDate: "2024-08",
    gpa: "",
    languageScore: "",
    militaryStatus: "군필",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "협의 필요",
    previousSalary: "",
    certifications: ["한국사능력검정", "MOS"],
    skills: ["PowerPoint", "Word", "Notion"],
    aiLevel: 2,
    englishLevel: 4,
    workType: "정규직",
    mainTasks: "졸업 프로젝트에서 설문조사 200건을 분석해 개선안을 제시하고 발표했어요.",
    previousExperience: "",
    selfIntroduction: "새로운 환경에 빠르게 적응하는 편이고, 데이터를 근거로 판단하는 습관을 기르고 있습니다.",
    availableStartDate: "2026-11-28",
    applicationSource: "회사 홈페이지",
    evaluationGrade: "",
    recruiterInCharge: "정하은",
    consentPrivacy: true,
    consentThirdParty: true,
    consentMarketing: false,
    addToTalentPool: true,
    stage: "면접",
    interviewAt: `${addDays(t, 1)}T14:00`,
  },
  {
    id: "cand-seed-9",
    createdAt: new Date(addDays(t, -28)).toISOString(),
    name: "서지경",
    birthYear: "2001",
    phone: "010-2296-3424",
    email: "c9@example.com",
    region: "대전",
    desiredRole: "개발",
    portfolioUrl: "https://example.com/cand-seed-9",
    desiredSalary: "2,800만원",
    educationLevel: "대졸",
    schoolName: "해솔대학교",
    major: "디자인학",
    graduationDate: "2025-08",
    gpa: "",
    languageScore: "",
    militaryStatus: "면제",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "가능",
    previousSalary: "",
    certifications: ["한국사능력검정", "전산회계"],
    skills: ["Notion", "SQL"],
    aiLevel: 1,
    englishLevel: 5,
    workType: "정규직",
    mainTasks: "졸업 프로젝트에서 설문조사 200건을 분석해 개선안을 제시하고 발표했어요.",
    previousExperience: "",
    selfIntroduction: "새로운 환경에 빠르게 적응하는 편이고, 데이터를 근거로 판단하는 습관을 기르고 있습니다.",
    availableStartDate: "2026-10-27",
    applicationSource: "지인 추천",
    evaluationGrade: "B",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: true,
    stage: "서류",
  },
  {
    id: "cand-seed-10",
    createdAt: new Date(addDays(t, -11)).toISOString(),
    name: "한윤원",
    birthYear: "2001",
    phone: "010-2333-3477",
    email: "c10@example.com",
    region: "인천",
    desiredRole: "인사/총무",
    portfolioUrl: "",
    desiredSalary: "3,400만원",
    educationLevel: "전문대졸",
    schoolName: "미르대학교",
    major: "디자인학",
    graduationDate: "2024-02",
    gpa: "3.5 / 4.5",
    languageScore: "",
    militaryStatus: "면제",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "가능",
    previousSalary: "",
    certifications: ["컴퓨터활용능력", "전산회계"],
    skills: ["SQL", "Excel", "PowerPoint"],
    aiLevel: 2,
    englishLevel: 2,
    workType: "정규직",
    mainTasks: "인턴십 기간 동안 데이터 정리와 보고서 작성을 지원하며 실무 툴 사용법을 익혔어요.",
    previousExperience: "",
    selfIntroduction: "배운 것을 실무에 바로 적용하고 싶어 지원했습니다. 꼼꼼함과 책임감을 강점으로 생각합니다.",
    availableStartDate: "2026-11-20",
    applicationSource: "회사 홈페이지",
    evaluationGrade: "",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "서류",
  },
  {
    id: "cand-seed-11",
    createdAt: new Date(addDays(t, -9)).toISOString(),
    name: "이도은",
    birthYear: "1999",
    phone: "010-2370-3530",
    email: "c11@example.com",
    region: "강원",
    desiredRole: "디자인",
    portfolioUrl: "",
    desiredSalary: "2,900만원",
    educationLevel: "대졸",
    schoolName: "도담대학교",
    major: "광고홍보학",
    graduationDate: "2026-02",
    gpa: "",
    languageScore: "토익 888",
    militaryStatus: "면제",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "가능",
    previousSalary: "",
    certifications: ["없음"],
    skills: ["SQL", "Word", "Notion"],
    aiLevel: 5,
    englishLevel: 4,
    workType: "정규직",
    mainTasks: "동아리 운영진으로 신입 부원 모집과 SNS 콘텐츠 제작을 맡아 팔로워를 두 배로 늘렸어요.",
    previousExperience: "",
    selfIntroduction: "새로운 환경에 빠르게 적응하는 편이고, 데이터를 근거로 판단하는 습관을 기르고 있습니다.",
    availableStartDate: "2026-10-26",
    applicationSource: "기타",
    evaluationGrade: "",
    recruiterInCharge: "박지훈",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: true,
    stage: "면접",
    interviewAt: `${addDays(t, 2)}T14:30`,
  },
  {
    id: "cand-seed-12",
    createdAt: new Date(addDays(t, -6)).toISOString(),
    name: "홍현결",
    birthYear: "1999",
    phone: "010-2407-3583",
    email: "c12@example.com",
    region: "서울",
    desiredRole: "영업",
    portfolioUrl: "",
    desiredSalary: "3,200만원",
    educationLevel: "대졸",
    schoolName: "청람대학교",
    major: "시각디자인학",
    graduationDate: "2024-08",
    gpa: "3.1 / 4.5",
    languageScore: "",
    militaryStatus: "미필",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "가능",
    previousSalary: "",
    certifications: ["MOS", "사회조사분석사"],
    skills: ["Slack", "Excel", "PowerPoint", "Word"],
    aiLevel: 3,
    englishLevel: 5,
    workType: "인턴",
    mainTasks: "교내 공모전에서 팀 프로젝트를 이끌며 자료 조사와 발표 자료 제작을 담당했어요.",
    previousExperience: "",
    selfIntroduction: "새로운 환경에 빠르게 적응하는 편이고, 데이터를 근거로 판단하는 습관을 기르고 있습니다.",
    availableStartDate: "2026-11-05",
    applicationSource: "채용사이트",
    evaluationGrade: "A",
    recruiterInCharge: "박지훈",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "최종",
  },
  {
    id: "cand-seed-13",
    createdAt: new Date(addDays(t, -24)).toISOString(),
    name: "전예경",
    birthYear: "2003",
    phone: "010-2444-3636",
    email: "c13@example.com",
    region: "강원",
    desiredRole: "고객지원",
    portfolioUrl: "https://example.com/cand-seed-13",
    desiredSalary: "3,100만원",
    educationLevel: "대졸",
    schoolName: "은강대학교",
    major: "경영학",
    graduationDate: "2025-02",
    gpa: "4.3 / 4.5",
    languageScore: "토익 835",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "가능",
    previousSalary: "",
    certifications: ["사회조사분석사"],
    skills: ["PowerPoint", "Excel", "SQL"],
    aiLevel: 1,
    englishLevel: 4,
    workType: "정규직",
    mainTasks: "졸업 프로젝트에서 설문조사 200건을 분석해 개선안을 제시하고 발표했어요.",
    previousExperience: "",
    selfIntroduction: "배운 것을 실무에 바로 적용하고 싶어 지원했습니다. 꼼꼼함과 책임감을 강점으로 생각합니다.",
    availableStartDate: "2026-12-03",
    applicationSource: "헤드헌터",
    evaluationGrade: "C",
    recruiterInCharge: "박지훈",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "면접",
    interviewAt: `${addDays(t, 3)}T10:30`,
  },
  {
    id: "cand-seed-14",
    createdAt: new Date(addDays(t, -42)).toISOString(),
    name: "한서아",
    birthYear: "2003",
    phone: "010-2481-3689",
    email: "c14@example.com",
    region: "경북",
    desiredRole: "디자인",
    portfolioUrl: "",
    desiredSalary: "3,200만원",
    educationLevel: "전문대졸",
    schoolName: "해솔대학교",
    major: "경제학",
    graduationDate: "2024-02",
    gpa: "",
    languageScore: "토익 654",
    militaryStatus: "군필",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "협의 필요",
    previousSalary: "",
    certifications: ["없음"],
    skills: ["Notion", "SQL", "Excel"],
    aiLevel: 4,
    englishLevel: 1,
    workType: "정규직",
    mainTasks: "학과 학생회에서 행사 기획과 예산 관리를 맡아 200명 규모 행사를 문제없이 운영했어요.",
    previousExperience: "",
    selfIntroduction: "새로운 환경에 빠르게 적응하는 편이고, 데이터를 근거로 판단하는 습관을 기르고 있습니다.",
    availableStartDate: "2026-11-08",
    applicationSource: "채용사이트",
    evaluationGrade: "",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: true,
    consentMarketing: true,
    addToTalentPool: false,
    stage: "서류",
  },
  {
    id: "cand-seed-15",
    createdAt: new Date(addDays(t, -38)).toISOString(),
    name: "이진안",
    birthYear: "1999",
    phone: "010-2518-3742",
    email: "c15@example.com",
    region: "경기",
    desiredRole: "운영/실행",
    portfolioUrl: "",
    desiredSalary: "3,000만원",
    educationLevel: "대졸",
    schoolName: "이음대학교",
    major: "시각디자인학",
    graduationDate: "2025-08",
    gpa: "",
    languageScore: "",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "신입",
    employmentStatus: "무직",
    recentCompany: "",
    department: "",
    position: "",
    joinDate: "",
    salaryNegotiable: "협의 필요",
    previousSalary: "",
    certifications: ["없음"],
    skills: ["Excel", "Word"],
    aiLevel: 5,
    englishLevel: 1,
    workType: "정규직",
    mainTasks: "학과 학생회에서 행사 기획과 예산 관리를 맡아 200명 규모 행사를 문제없이 운영했어요.",
    previousExperience: "",
    selfIntroduction: "학업과 대외활동을 병행하며 시간관리와 협업 능력을 키워왔습니다.",
    availableStartDate: "2026-12-21",
    applicationSource: "회사 홈페이지",
    evaluationGrade: "",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: true,
    consentMarketing: true,
    addToTalentPool: false,
    stage: "서류",
  },
  {
    id: "cand-seed-16",
    createdAt: new Date(addDays(t, -17)).toISOString(),
    name: "정수결",
    birthYear: "1987",
    phone: "010-2555-3795",
    email: "c16@example.com",
    region: "울산",
    desiredRole: "고객지원",
    portfolioUrl: "",
    desiredSalary: "5,000만원",
    educationLevel: "대졸",
    schoolName: "한백대학교",
    major: "통계학",
    graduationDate: "2009-02",
    gpa: "",
    languageScore: "토익 710",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "1~3년",
    employmentStatus: "무직",
    recentCompany: "해담커머스",
    department: "고객지원팀",
    position: "대리",
    joinDate: "2022-09-25",
    salaryNegotiable: "협의 필요",
    previousSalary: "3,700만원",
    certifications: ["MOS"],
    skills: ["Excel", "Notion", "PowerPoint"],
    aiLevel: 3,
    englishLevel: 3,
    workType: "정규직",
    mainTasks: "담당 부서의 연간 운영 계획을 수립하고 분기별 실적을 관리했어요.",
    previousExperience: "",
    selfIntroduction: "실무에서 쌓은 경험을 바탕으로 더 큰 조직에서 성장하고 싶어 지원했습니다.",
    availableStartDate: "2026-12-01",
    applicationSource: "지인 추천",
    evaluationGrade: "S",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "서류",
  },
  {
    id: "cand-seed-17",
    createdAt: new Date(addDays(t, -3)).toISOString(),
    name: "한지경",
    birthYear: "1992",
    phone: "010-2592-3848",
    email: "c17@example.com",
    region: "울산",
    desiredRole: "마케팅",
    portfolioUrl: "",
    desiredSalary: "5,700만원",
    educationLevel: "석사",
    schoolName: "도담대학교",
    major: "심리학",
    graduationDate: "2015-02",
    gpa: "",
    languageScore: "",
    militaryStatus: "군필",
    veteranStatus: "해당없음",
    totalExperience: "1년 미만",
    employmentStatus: "재직중",
    recentCompany: "온새로시스템",
    department: "개발팀",
    position: "과장",
    joinDate: "2020-09-25",
    salaryNegotiable: "가능",
    previousSalary: "3,200만원",
    certifications: ["전산회계", "MOS"],
    skills: ["Notion", "PowerPoint", "SQL"],
    aiLevel: 4,
    englishLevel: 2,
    workType: "정규직",
    mainTasks: "팀 내 반복 업무를 자동화해 주간 보고 작성 시간을 절반으로 줄였어요.",
    previousExperience: "",
    selfIntroduction: "다양한 프로젝트 경험을 통해 유연한 커뮤니케이션 능력을 길러왔습니다.",
    availableStartDate: "2026-12-05",
    applicationSource: "지인 추천",
    evaluationGrade: "",
    recruiterInCharge: "정하은",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "최종",
  },
  {
    id: "cand-seed-18",
    createdAt: new Date(addDays(t, -33)).toISOString(),
    name: "장현호",
    birthYear: "1995",
    phone: "010-2629-3901",
    email: "c18@example.com",
    region: "충남",
    desiredRole: "마케팅",
    portfolioUrl: "https://example.com/cand-seed-18",
    desiredSalary: "4,400만원",
    educationLevel: "전문대졸",
    schoolName: "도담대학교",
    major: "경영학",
    graduationDate: "2007-02",
    gpa: "",
    languageScore: "토익 721",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "7~10년",
    employmentStatus: "퇴사",
    recentCompany: "다인마케팅",
    department: "개발팀",
    position: "팀장",
    joinDate: "2022-09-25",
    salaryNegotiable: "협의 필요",
    previousSalary: "3,600만원",
    certifications: ["MOS", "전산회계"],
    skills: ["Excel", "SQL", "Word", "Notion"],
    aiLevel: 4,
    englishLevel: 4,
    workType: "정규직",
    mainTasks: "신규 프로젝트 런칭을 담당하며 유관 부서와의 협업을 조율했어요.",
    previousExperience: "담당 부서의 연간 운영 계획을 수립하고 분기별 실적을 관리했어요.",
    selfIntroduction: "문제를 발견하면 끝까지 개선하는 편이고, 팀 성과를 우선으로 생각합니다.",
    availableStartDate: "2026-12-08",
    applicationSource: "채용사이트",
    evaluationGrade: "B",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "합격",
  },
  {
    id: "cand-seed-19",
    createdAt: new Date(addDays(t, -26)).toISOString(),
    name: "서예성",
    birthYear: "1988",
    phone: "010-2666-3954",
    email: "c19@example.com",
    region: "부산",
    desiredRole: "디자인",
    portfolioUrl: "",
    desiredSalary: "5,800만원",
    educationLevel: "고졸",
    schoolName: "한백대학교",
    major: "산업공학",
    graduationDate: "2017-08",
    gpa: "",
    languageScore: "",
    militaryStatus: "미필",
    veteranStatus: "해당없음",
    totalExperience: "1~3년",
    employmentStatus: "재직중",
    recentCompany: "가온파트너스",
    department: "운영팀",
    position: "사원",
    joinDate: "2021-09-25",
    salaryNegotiable: "가능",
    previousSalary: "4,300만원",
    certifications: ["MOS", "한국사능력검정"],
    skills: ["Notion", "Word", "PowerPoint", "Excel"],
    aiLevel: null,
    englishLevel: 1,
    workType: "정규직",
    mainTasks: "팀 내 반복 업무를 자동화해 주간 보고 작성 시간을 절반으로 줄였어요.",
    previousExperience: "신입 사원 교육 프로그램을 설계하고 운영해 적응 기간을 단축했어요.",
    selfIntroduction: "다양한 프로젝트 경험을 통해 유연한 커뮤니케이션 능력을 길러왔습니다.",
    availableStartDate: "2026-10-29",
    applicationSource: "기타",
    evaluationGrade: "",
    recruiterInCharge: "정하은",
    consentPrivacy: true,
    consentThirdParty: true,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "불합격",
  },
  {
    id: "cand-seed-20",
    createdAt: new Date(addDays(t, -3)).toISOString(),
    name: "홍지원",
    birthYear: "1996",
    phone: "010-2703-4007",
    email: "c20@example.com",
    region: "대구",
    desiredRole: "영업",
    portfolioUrl: "",
    desiredSalary: "6,100만원",
    educationLevel: "고졸",
    schoolName: "도담대학교",
    major: "심리학",
    graduationDate: "2015-02",
    gpa: "",
    languageScore: "토익 847",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "1~3년",
    employmentStatus: "재직중",
    recentCompany: "별빛리테일",
    department: "인사팀",
    position: "과장",
    joinDate: "2021-09-25",
    salaryNegotiable: "가능",
    previousSalary: "4,100만원",
    certifications: ["컴퓨터활용능력"],
    skills: ["Notion", "PowerPoint", "SQL"],
    aiLevel: 2,
    englishLevel: 4,
    workType: "정규직",
    mainTasks: "팀 내 반복 업무를 자동화해 주간 보고 작성 시간을 절반으로 줄였어요.",
    previousExperience: "신입 사원 교육 프로그램을 설계하고 운영해 적응 기간을 단축했어요.",
    selfIntroduction: "다양한 프로젝트 경험을 통해 유연한 커뮤니케이션 능력을 길러왔습니다.",
    availableStartDate: "2026-12-12",
    applicationSource: "지인 추천",
    evaluationGrade: "",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: true,
    addToTalentPool: false,
    stage: "서류",
  },
  {
    id: "cand-seed-21",
    createdAt: new Date(addDays(t, -41)).toISOString(),
    name: "한도윤",
    birthYear: "1987",
    phone: "010-2740-4060",
    email: "c21@example.com",
    region: "전북",
    desiredRole: "운영/실행",
    portfolioUrl: "",
    desiredSalary: "4,600만원",
    educationLevel: "전문대졸",
    schoolName: "이음대학교",
    major: "통계학",
    graduationDate: "2014-08",
    gpa: "",
    languageScore: "",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "1년 미만",
    employmentStatus: "재직중",
    recentCompany: "청솔디자인",
    department: "개발팀",
    position: "과장",
    joinDate: "2021-09-25",
    salaryNegotiable: "가능",
    previousSalary: "3,700만원",
    certifications: ["MOS", "전산회계"],
    skills: ["Excel", "PowerPoint", "Notion"],
    aiLevel: 1,
    englishLevel: 4,
    workType: "정규직",
    mainTasks: "담당 부서의 연간 운영 계획을 수립하고 분기별 실적을 관리했어요.",
    previousExperience: "",
    selfIntroduction: "실무에서 쌓은 경험을 바탕으로 더 큰 조직에서 성장하고 싶어 지원했습니다.",
    availableStartDate: "2026-12-10",
    applicationSource: "회사 홈페이지",
    evaluationGrade: "",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: true,
    stage: "서류",
  },
  {
    id: "cand-seed-22",
    createdAt: new Date(addDays(t, -17)).toISOString(),
    name: "배시솔",
    birthYear: "1994",
    phone: "010-2777-4113",
    email: "c22@example.com",
    region: "제주",
    desiredRole: "운영/실행",
    portfolioUrl: "",
    desiredSalary: "5,900만원",
    educationLevel: "석사",
    schoolName: "가온대학교",
    major: "전자공학",
    graduationDate: "2007-08",
    gpa: "",
    languageScore: "토익 944",
    militaryStatus: "면제",
    veteranStatus: "해당없음",
    totalExperience: "7~10년",
    employmentStatus: "퇴사",
    recentCompany: "다인마케팅",
    department: "인사팀",
    position: "대리",
    joinDate: "2022-09-25",
    salaryNegotiable: "가능",
    previousSalary: "4,600만원",
    certifications: ["정보처리기사"],
    skills: ["Slack", "SQL", "Notion"],
    aiLevel: null,
    englishLevel: null,
    workType: "정규직",
    mainTasks: "신입 사원 교육 프로그램을 설계하고 운영해 적응 기간을 단축했어요.",
    previousExperience: "담당 부서의 연간 운영 계획을 수립하고 분기별 실적을 관리했어요.",
    selfIntroduction: "실무에서 쌓은 경험을 바탕으로 더 큰 조직에서 성장하고 싶어 지원했습니다.",
    availableStartDate: "2026-12-11",
    applicationSource: "기타",
    evaluationGrade: "",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "서류",
  },
  {
    id: "cand-seed-23",
    createdAt: new Date(addDays(t, -34)).toISOString(),
    name: "강민안",
    birthYear: "1991",
    phone: "010-2814-4166",
    email: "c23@example.com",
    region: "울산",
    desiredRole: "고객지원",
    portfolioUrl: "",
    desiredSalary: "6,000만원",
    educationLevel: "대졸",
    schoolName: "해솔대학교",
    major: "디자인학",
    graduationDate: "2015-08",
    gpa: "",
    languageScore: "토익 725",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "10년 이상",
    employmentStatus: "퇴사",
    recentCompany: "이든컨설팅",
    department: "영업팀",
    position: "사원",
    joinDate: "2021-09-25",
    salaryNegotiable: "가능",
    previousSalary: "5,200만원",
    certifications: ["한국사능력검정"],
    skills: ["Notion", "PowerPoint"],
    aiLevel: 5,
    englishLevel: null,
    workType: "정규직",
    mainTasks: "고객 데이터를 분석해 프로세스를 개선하고 처리 시간을 단축했어요.",
    previousExperience: "",
    selfIntroduction: "문제를 발견하면 끝까지 개선하는 편이고, 팀 성과를 우선으로 생각합니다.",
    availableStartDate: "2026-11-11",
    applicationSource: "회사 홈페이지",
    evaluationGrade: "A",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: true,
    addToTalentPool: true,
    stage: "서류",
  },
  {
    id: "cand-seed-24",
    createdAt: new Date(addDays(t, -5)).toISOString(),
    name: "강현빈",
    birthYear: "1994",
    phone: "010-2851-4219",
    email: "c24@example.com",
    region: "강원",
    desiredRole: "영업",
    portfolioUrl: "",
    desiredSalary: "6,300만원",
    educationLevel: "전문대졸",
    schoolName: "청람대학교",
    major: "전자공학",
    graduationDate: "2018-02",
    gpa: "",
    languageScore: "",
    militaryStatus: "미필",
    veteranStatus: "해당없음",
    totalExperience: "1년 미만",
    employmentStatus: "재직중",
    recentCompany: "한결소프트",
    department: "재무팀",
    position: "팀장",
    joinDate: "2022-09-25",
    salaryNegotiable: "협의 필요",
    previousSalary: "4,500만원",
    certifications: ["한국사능력검정"],
    skills: ["PowerPoint", "Slack", "Notion", "Word"],
    aiLevel: 4,
    englishLevel: 1,
    workType: "정규직",
    mainTasks: "신입 사원 교육 프로그램을 설계하고 운영해 적응 기간을 단축했어요.",
    previousExperience: "",
    selfIntroduction: "문제를 발견하면 끝까지 개선하는 편이고, 팀 성과를 우선으로 생각합니다.",
    availableStartDate: "2026-12-13",
    applicationSource: "지인 추천",
    evaluationGrade: "B",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: true,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "면접",
    interviewAt: `${addDays(t, -1)}T16:00`,
  },
  {
    id: "cand-seed-25",
    createdAt: new Date(addDays(t, -24)).toISOString(),
    name: "서지솔",
    birthYear: "1996",
    phone: "010-2888-4272",
    email: "c25@example.com",
    region: "대전",
    desiredRole: "인사/총무",
    portfolioUrl: "https://example.com/cand-seed-25",
    desiredSalary: "4,700만원",
    educationLevel: "대졸",
    schoolName: "도담대학교",
    major: "광고홍보학",
    graduationDate: "2018-08",
    gpa: "",
    languageScore: "",
    militaryStatus: "군필",
    veteranStatus: "해당없음",
    totalExperience: "5~7년",
    employmentStatus: "재직중",
    recentCompany: "별빛리테일",
    department: "경영기획팀",
    position: "대리",
    joinDate: "2020-09-25",
    salaryNegotiable: "가능",
    previousSalary: "5,600만원",
    certifications: ["MOS"],
    skills: ["Slack", "PowerPoint"],
    aiLevel: 2,
    englishLevel: null,
    workType: "정규직",
    mainTasks: "팀 내 반복 업무를 자동화해 주간 보고 작성 시간을 절반으로 줄였어요.",
    previousExperience: "담당 부서의 연간 운영 계획을 수립하고 분기별 실적을 관리했어요.",
    selfIntroduction: "문제를 발견하면 끝까지 개선하는 편이고, 팀 성과를 우선으로 생각합니다.",
    availableStartDate: "2026-12-04",
    applicationSource: "채용사이트",
    evaluationGrade: "B",
    recruiterInCharge: "최지우",
    consentPrivacy: true,
    consentThirdParty: true,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "불합격",
  },
  {
    id: "cand-seed-26",
    createdAt: new Date(addDays(t, -9)).toISOString(),
    name: "강서원",
    birthYear: "1991",
    phone: "010-2925-4325",
    email: "c26@example.com",
    region: "대전",
    desiredRole: "영업",
    portfolioUrl: "https://example.com/cand-seed-26",
    desiredSalary: "6,600만원",
    educationLevel: "전문대졸",
    schoolName: "이음대학교",
    major: "광고홍보학",
    graduationDate: "2017-02",
    gpa: "",
    languageScore: "",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "7~10년",
    employmentStatus: "재직중",
    recentCompany: "이든컨설팅",
    department: "디자인팀",
    position: "과장",
    joinDate: "2023-09-25",
    salaryNegotiable: "협의 필요",
    previousSalary: "5,200만원",
    certifications: ["정보처리기사", "컴퓨터활용능력"],
    skills: ["Notion", "Slack"],
    aiLevel: 5,
    englishLevel: 2,
    workType: "정규직",
    mainTasks: "고객 데이터를 분석해 프로세스를 개선하고 처리 시간을 단축했어요.",
    previousExperience: "고객 데이터를 분석해 프로세스를 개선하고 처리 시간을 단축했어요.",
    selfIntroduction: "문제를 발견하면 끝까지 개선하는 편이고, 팀 성과를 우선으로 생각합니다.",
    availableStartDate: "2026-11-04",
    applicationSource: "기타",
    evaluationGrade: "S",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: true,
    consentMarketing: true,
    addToTalentPool: false,
    stage: "서류",
  },
  {
    id: "cand-seed-27",
    createdAt: new Date(addDays(t, -11)).toISOString(),
    name: "최우건",
    birthYear: "1988",
    phone: "010-2962-4378",
    email: "c27@example.com",
    region: "경기",
    desiredRole: "마케팅",
    portfolioUrl: "",
    desiredSalary: "4,100만원",
    educationLevel: "대졸",
    schoolName: "가온대학교",
    major: "컴퓨터공학",
    graduationDate: "2007-08",
    gpa: "",
    languageScore: "",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "10년 이상",
    employmentStatus: "무직",
    recentCompany: "예시물산",
    department: "영업팀",
    position: "주임",
    joinDate: "2022-09-25",
    salaryNegotiable: "협의 필요",
    previousSalary: "5,400만원",
    certifications: ["사회조사분석사", "MOS"],
    skills: ["SQL", "Word", "Notion"],
    aiLevel: null,
    englishLevel: 5,
    workType: "정규직",
    mainTasks: "고객 데이터를 분석해 프로세스를 개선하고 처리 시간을 단축했어요.",
    previousExperience: "담당 부서의 연간 운영 계획을 수립하고 분기별 실적을 관리했어요.",
    selfIntroduction: "다양한 프로젝트 경험을 통해 유연한 커뮤니케이션 능력을 길러왔습니다.",
    availableStartDate: "2026-10-25",
    applicationSource: "기타",
    evaluationGrade: "B",
    recruiterInCharge: "정하은",
    consentPrivacy: true,
    consentThirdParty: true,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "면접",
    interviewAt: `${addDays(t, 0)}T16:30`,
  },
  {
    id: "cand-seed-28",
    createdAt: new Date(addDays(t, -11)).toISOString(),
    name: "신하원",
    birthYear: "1996",
    phone: "010-2999-4431",
    email: "c28@example.com",
    region: "경북",
    desiredRole: "개발",
    portfolioUrl: "https://example.com/cand-seed-28",
    desiredSalary: "3,900만원",
    educationLevel: "대졸",
    schoolName: "이음대학교",
    major: "전자공학",
    graduationDate: "2017-02",
    gpa: "",
    languageScore: "",
    militaryStatus: "비대상",
    veteranStatus: "해당없음",
    totalExperience: "1~3년",
    employmentStatus: "재직중",
    recentCompany: "온새로시스템",
    department: "운영팀",
    position: "과장",
    joinDate: "2023-09-25",
    salaryNegotiable: "가능",
    previousSalary: "3,900만원",
    certifications: ["MOS"],
    skills: ["PowerPoint", "Notion", "SQL", "Slack"],
    aiLevel: 5,
    englishLevel: 1,
    workType: "정규직",
    mainTasks: "신규 프로젝트 런칭을 담당하며 유관 부서와의 협업을 조율했어요.",
    previousExperience: "신입 사원 교육 프로그램을 설계하고 운영해 적응 기간을 단축했어요.",
    selfIntroduction: "문제를 발견하면 끝까지 개선하는 편이고, 팀 성과를 우선으로 생각합니다.",
    availableStartDate: "2026-11-24",
    applicationSource: "지인 추천",
    evaluationGrade: "C",
    recruiterInCharge: "정하은",
    consentPrivacy: true,
    consentThirdParty: true,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "면접",
    interviewAt: `${addDays(t, 1)}T14:00`,
  },
  {
    id: "cand-seed-29",
    createdAt: new Date(addDays(t, -11)).toISOString(),
    name: "전예훈",
    birthYear: "1994",
    phone: "010-3036-4484",
    email: "c29@example.com",
    region: "경기",
    desiredRole: "개발",
    portfolioUrl: "",
    desiredSalary: "5,400만원",
    educationLevel: "대졸",
    schoolName: "청람대학교",
    major: "행정학",
    graduationDate: "2014-02",
    gpa: "",
    languageScore: "토익 823",
    militaryStatus: "군필",
    veteranStatus: "해당없음",
    totalExperience: "5~7년",
    employmentStatus: "재직중",
    recentCompany: "청솔디자인",
    department: "경영기획팀",
    position: "사원",
    joinDate: "2024-09-24",
    salaryNegotiable: "가능",
    previousSalary: "5,800만원",
    certifications: ["MOS"],
    skills: ["Excel", "PowerPoint"],
    aiLevel: null,
    englishLevel: 3,
    workType: "정규직",
    mainTasks: "신규 프로젝트 런칭을 담당하며 유관 부서와의 협업을 조율했어요.",
    previousExperience: "담당 부서의 연간 운영 계획을 수립하고 분기별 실적을 관리했어요.",
    selfIntroduction: "다양한 프로젝트 경험을 통해 유연한 커뮤니케이션 능력을 길러왔습니다.",
    availableStartDate: "2026-11-25",
    applicationSource: "지인 추천",
    evaluationGrade: "C",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: false,
    stage: "서류",
  },
  {
    id: "cand-seed-30",
    createdAt: new Date(addDays(t, -20)).toISOString(),
    name: "윤진호",
    birthYear: "1990",
    phone: "010-3073-4537",
    email: "c30@example.com",
    region: "서울",
    desiredRole: "기획/전략",
    portfolioUrl: "",
    desiredSalary: "6,600만원",
    educationLevel: "석사",
    schoolName: "가온대학교",
    major: "행정학",
    graduationDate: "2014-08",
    gpa: "",
    languageScore: "토익 927",
    militaryStatus: "면제",
    veteranStatus: "해당없음",
    totalExperience: "10년 이상",
    employmentStatus: "재직중",
    recentCompany: "해담커머스",
    department: "재무팀",
    position: "사원",
    joinDate: "2023-09-25",
    salaryNegotiable: "가능",
    previousSalary: "3,900만원",
    certifications: ["컴퓨터활용능력"],
    skills: ["Notion", "SQL", "Excel", "PowerPoint"],
    aiLevel: 1,
    englishLevel: 1,
    workType: "정규직",
    mainTasks: "담당 부서의 연간 운영 계획을 수립하고 분기별 실적을 관리했어요.",
    previousExperience: "",
    selfIntroduction: "실무에서 쌓은 경험을 바탕으로 더 큰 조직에서 성장하고 싶어 지원했습니다.",
    availableStartDate: "2026-12-03",
    applicationSource: "회사 홈페이지",
    evaluationGrade: "",
    recruiterInCharge: "",
    consentPrivacy: true,
    consentThirdParty: false,
    consentMarketing: false,
    addToTalentPool: true,
    stage: "합격",
  },
];
