import type { InterviewAssignment } from "./interview-scheduling";
import type { InterviewEvaluation } from "./interview-evaluation";
import { addDays, today } from "./date";

const t = today();

// 지금 지원자 중 이미 "면접" 단계를 지나 최종/합격/불합격까지 진행된
// 9명은, 논리적으로 오늘 이전에 이미 면접을 봤어야 한다. 그 과거 배정과
// 평가 기록을 시드로 채워서, 면접관 관리·편향 체크가 "오늘 처음 도는
// 화면"이 아니라 누적된 이력 위에서 보이도록 한다. 앞으로 새로 자동
// 배정을 돌리면 그 결과는 이 과거 이력에 더해져 쌓인다.

export const seedInterviewAssignments: InterviewAssignment[] = [
  {
    candidateId: "cand-seed-4",
    panelId: "panel-hist-cand-seed-4",
    internalInterviewer: "김도현",
    externalInterviewer: "외부 면접관 A",
    room: "회의실 A",
    date: addDays(t, -35),
    startTime: "10:00",
    endTime: "10:30",
  },
  {
    candidateId: "cand-seed-18",
    panelId: "panel-hist-cand-seed-18",
    internalInterviewer: "서준영",
    externalInterviewer: "외부 면접관 B",
    room: "회의실 B",
    date: addDays(t, -20),
    startTime: "10:00",
    endTime: "10:30",
  },
  {
    candidateId: "cand-seed-30",
    panelId: "panel-hist-cand-seed-30",
    internalInterviewer: "최수빈",
    externalInterviewer: "외부 면접관 C",
    room: "회의실 C",
    date: addDays(t, -14),
    startTime: "10:00",
    endTime: "10:30",
  },
  {
    candidateId: "cand-seed-1",
    panelId: "panel-hist-cand-seed-1",
    internalInterviewer: "김도현",
    externalInterviewer: "외부 면접관 B",
    room: "회의실 A",
    date: addDays(t, -10),
    startTime: "10:00",
    endTime: "10:30",
  },
  {
    candidateId: "cand-seed-3",
    panelId: "panel-hist-cand-seed-3",
    internalInterviewer: "박지훈",
    externalInterviewer: "외부 면접관 C",
    room: "회의실 D",
    date: addDays(t, -28),
    startTime: "10:00",
    endTime: "10:30",
  },
  {
    candidateId: "cand-seed-12",
    panelId: "panel-hist-cand-seed-12",
    internalInterviewer: "서준영",
    externalInterviewer: "외부 면접관 D",
    room: "회의실 B",
    date: addDays(t, -7),
    startTime: "10:00",
    endTime: "10:30",
  },
  {
    candidateId: "cand-seed-17",
    panelId: "panel-hist-cand-seed-17",
    internalInterviewer: "이하은",
    externalInterviewer: "외부 면접관 A",
    room: "회의실 A",
    date: addDays(t, -42),
    startTime: "10:00",
    endTime: "10:30",
  },
  {
    candidateId: "cand-seed-19",
    panelId: "panel-hist-cand-seed-19",
    internalInterviewer: "최수빈",
    externalInterviewer: "외부 면접관 D",
    room: "회의실 C",
    date: addDays(t, -24),
    startTime: "10:00",
    endTime: "10:30",
  },
  {
    candidateId: "cand-seed-25",
    panelId: "panel-hist-cand-seed-25",
    internalInterviewer: "박지훈",
    externalInterviewer: "외부 면접관 B",
    room: "회의실 D",
    date: addDays(t, -17),
    startTime: "10:00",
    endTime: "10:30",
  },
];

export const seedInterviewEvaluations: InterviewEvaluation[] = [
  {
    candidateId: "cand-seed-4",
    interviewerName: "김도현",
    score: 88,
    breakdown: { jobFit: 22, communication: 23, problemSolving: 21, cultureFit: 22 },
    comment: "포트폴리오 완성도가 높고 커뮤니케이션도 매끄러움.",
    evaluatedAt: new Date(addDays(t, -35)).toISOString(),
  },
  {
    candidateId: "cand-seed-4",
    interviewerName: "외부 면접관 A",
    score: 84,
    breakdown: { jobFit: 20, communication: 22, problemSolving: 21, cultureFit: 21 },
    comment: "디자인 감각과 실무 적용력이 뛰어남.",
    evaluatedAt: new Date(addDays(t, -35)).toISOString(),
  },
  {
    candidateId: "cand-seed-18",
    interviewerName: "서준영",
    score: 83,
    breakdown: { jobFit: 21, communication: 20, problemSolving: 22, cultureFit: 20 },
    comment: "마케팅 캠페인 경험이 구체적이고 성과 지표 제시가 명확함.",
    evaluatedAt: new Date(addDays(t, -20)).toISOString(),
  },
  {
    candidateId: "cand-seed-18",
    interviewerName: "외부 면접관 B",
    score: 88,
    breakdown: { jobFit: 23, communication: 21, problemSolving: 22, cultureFit: 22 },
    comment: "데이터 기반 의사결정 역량이 인상적.",
    evaluatedAt: new Date(addDays(t, -20)).toISOString(),
  },
  {
    candidateId: "cand-seed-30",
    interviewerName: "최수빈",
    score: 79,
    breakdown: { jobFit: 20, communication: 19, problemSolving: 21, cultureFit: 19 },
    comment: "전략 기획 사고가 체계적임.",
    evaluatedAt: new Date(addDays(t, -14)).toISOString(),
  },
  {
    candidateId: "cand-seed-30",
    interviewerName: "외부 면접관 C",
    score: 82,
    breakdown: { jobFit: 21, communication: 20, problemSolving: 20, cultureFit: 21 },
    comment: "논리 전개가 명확하고 협업 경험이 풍부함.",
    evaluatedAt: new Date(addDays(t, -14)).toISOString(),
  },
  {
    candidateId: "cand-seed-1",
    interviewerName: "김도현",
    score: 68,
    breakdown: { jobFit: 17, communication: 18, problemSolving: 16, cultureFit: 17 },
    comment: "영업 목표 달성 경험은 좋으나 신입이라 실전 적용은 지켜볼 필요.",
    evaluatedAt: new Date(addDays(t, -10)).toISOString(),
  },
  {
    candidateId: "cand-seed-1",
    interviewerName: "외부 면접관 B",
    score: 69,
    breakdown: { jobFit: 18, communication: 17, problemSolving: 18, cultureFit: 16 },
    comment: "적극적인 태도, 성장 가능성 있음.",
    evaluatedAt: new Date(addDays(t, -10)).toISOString(),
  },
  {
    candidateId: "cand-seed-3",
    interviewerName: "박지훈",
    score: 75,
    breakdown: { jobFit: 19, communication: 18, problemSolving: 20, cultureFit: 18 },
    comment: "기술 深度가 있고 문제 해결 과정을 논리적으로 설명함.",
    evaluatedAt: new Date(addDays(t, -28)).toISOString(),
  },
  {
    candidateId: "cand-seed-3",
    interviewerName: "외부 면접관 C",
    score: 71,
    breakdown: { jobFit: 17, communication: 19, problemSolving: 18, cultureFit: 17 },
    comment: "코드 품질에 대한 고민이 느껴짐.",
    evaluatedAt: new Date(addDays(t, -28)).toISOString(),
  },
  {
    candidateId: "cand-seed-12",
    interviewerName: "서준영",
    score: 72,
    breakdown: { jobFit: 18, communication: 17, problemSolving: 19, cultureFit: 18 },
    comment: "영업 프로세스 이해도가 높음.",
    evaluatedAt: new Date(addDays(t, -7)).toISOString(),
  },
  {
    candidateId: "cand-seed-12",
    interviewerName: "외부 면접관 D",
    score: 73,
    breakdown: { jobFit: 19, communication: 18, problemSolving: 17, cultureFit: 19 },
    comment: "고객 대응 사례가 구체적임.",
    evaluatedAt: new Date(addDays(t, -7)).toISOString(),
  },
  {
    candidateId: "cand-seed-17",
    interviewerName: "이하은",
    score: 72,
    breakdown: { jobFit: 18, communication: 19, problemSolving: 18, cultureFit: 17 },
    comment: "마케팅 데이터 분석 경험이 실무에 바로 쓰일 수준.",
    evaluatedAt: new Date(addDays(t, -42)).toISOString(),
  },
  {
    candidateId: "cand-seed-17",
    interviewerName: "외부 면접관 A",
    score: 72,
    breakdown: { jobFit: 18, communication: 17, problemSolving: 19, cultureFit: 18 },
    comment: "캠페인 기획 아이디어가 참신함.",
    evaluatedAt: new Date(addDays(t, -42)).toISOString(),
  },
  {
    candidateId: "cand-seed-19",
    interviewerName: "최수빈",
    score: 42,
    breakdown: { jobFit: 10, communication: 12, problemSolving: 9, cultureFit: 11 },
    comment: "포트폴리오가 직무와 결이 맞지 않음.",
    evaluatedAt: new Date(addDays(t, -24)).toISOString(),
  },
  {
    candidateId: "cand-seed-19",
    interviewerName: "외부 면접관 D",
    score: 42,
    breakdown: { jobFit: 11, communication: 10, problemSolving: 12, cultureFit: 9 },
    comment: "디자인 툴 활용 능력이 기대에 못 미침.",
    evaluatedAt: new Date(addDays(t, -24)).toISOString(),
  },
  {
    candidateId: "cand-seed-25",
    interviewerName: "박지훈",
    score: 35,
    breakdown: { jobFit: 8, communication: 10, problemSolving: 9, cultureFit: 8 },
    comment: "인사 직무 이해도가 부족함.",
    evaluatedAt: new Date(addDays(t, -17)).toISOString(),
  },
  {
    candidateId: "cand-seed-25",
    interviewerName: "외부 면접관 B",
    score: 36,
    breakdown: { jobFit: 9, communication: 8, problemSolving: 10, cultureFit: 9 },
    comment: "구체적인 실무 사례 제시가 어려웠음.",
    evaluatedAt: new Date(addDays(t, -17)).toISOString(),
  },
];
